import {getBrain,getLedger,readBrainSettings,saveBrainSettings,resolveForecast,readerKey,getProfile,saveProfile,personalBrief} from '@/lib/forecast';
import {localIntelligence} from '@/lib/local-intelligence';
import {searchArticles} from '@/lib/article-search';
import {readDeals,saveDeals,publicDeals,previewDeal} from '@/lib/deals';
import {readStreamingSettings,saveStreamingSettings,publicStreamingSettings,transcribeChunk,TRANSCRIPTION_MAX_BYTES} from '@/lib/streaming';
import {readRewardSettings,saveRewardSettings,publicRewardSettings,startRewardSession,heartbeatRewardSession,claimReward} from '@/lib/reward-ads';
import {getIntelligence} from '@/lib/intelligence';
import {readVideoSettings,saveVideoSettings,publicVideoSettings} from '@/lib/video';
import {socialStatus,saveDistributionSettings,saveXClient,beginXOAuth,completeXOAuth,disconnectX,resolveXDelivery,exportBriefHtml,exportBriefText} from '@/lib/social-publishing';
import {renderIntelligenceMap} from '@/lib/intelligence-map';
import {db,runtime,clean,safeUrl,setting,saveSetting,getEdition,getArticles,getHeadlines,getMarkets,getPoll,pollCounts,rateLimit,requireAdmin,requireMaintenance,maintenance,sendEmail,emailLayout,escape,now,log,fetchRSS} from '@/lib/news-server';
import {defaultAds,sourceCandidates,categories,sourceDirectory} from '@/lib/news-data';
import {normalizeAdvertisers} from '@/lib/advertising-core';
import {reserveAdSlots,getAdvertisingStats} from '@/lib/advertising';
import {validateSources} from '@/lib/publisher-settings';
const socialContext=()=>({db:db(),env:runtime(),siteOrigin:runtime().SITE_ORIGIN||''});
export const dynamic='force-dynamic';
const json=(value:unknown,status=200,headers:Record<string,string>={})=>Response.json(value,{status,headers:{'Cache-Control':'no-store',...headers}});
const readerError=(message:string,status:number)=>status===401?'Sign in to save or view your private profile.':status===403?'This request is not available.':status===429?'Please wait a moment before trying again.':message.includes('five-digit')?'Enter a five-digit US ZIP code.':'This service is temporarily unavailable. Please try again.';
const path=(r:Request)=>new URL(r.url).pathname.replace(/^\/api\//,'');
const cookie=(r:Request,name:string)=>r.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1);
async function hash(s:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(b=>b.toString(16).padStart(2,'0')).join('')}
const page=(title:string,body:string)=>new Response('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+' · Jew Knows</title></head><body style="margin:0;padding:60px 24px;font-family:Arial;color:#141517;background:white"><div style="max-width:700px;margin:auto"><a href="/" style="font-family:Georgia;font-weight:bold;font-size:40px;color:#141517;text-decoration:none">Jew Knows<span style="color:#284ef0">.</span></a><h1 style="font-family:Georgia;font-weight:400;font-size:45px;margin-top:50px">'+title+'</h1>'+body+'<p style="margin-top:35px"><a href="/" style="color:#284ef0">Return to the edition</a></p></div></body></html>',{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer'}});
export async function GET(request:Request){try{const p=path(request),url=new URL(request.url);
 if(p==='brain'){let canRefresh=false;try{requireAdmin(request);canRefresh=true}catch{}return json({...await getBrain({db:db()}),canRefresh});}
 if(p==='ledger')return json(await getLedger({db:db()},url.searchParams.get('event')||undefined,Number(url.searchParams.get('page'))||1));
 if(p==='local'){await rateLimit(request,'local-context',30);return json(await localIntelligence({db:db()},url.searchParams.get('zip')||''));}
 if(p==='profile')return json(await getProfile({db:db()},await readerKey(request)));
 if(p==='admin/brain'){requireAdmin(request);return json({settings:await readBrainSettings({db:db()}),ledger:await getLedger({db:db()})});}
 if(p==='search')return json(await searchArticles(db(),url.searchParams.get('q')||'',Number(url.searchParams.get('page'))||1));
 if(p==='deals')return json(publicDeals(await readDeals(db())));
 if(p==='streaming')return json(publicStreamingSettings(await readStreamingSettings(db()),!!runtime().OPENAI_API_KEY));
 if(p==='rewards')return json(publicRewardSettings(await readRewardSettings({db:db()})));
 if(p==='admin/deals'){requireAdmin(request);return json(await readDeals(db()))}
 if(p==='admin/streaming'){requireAdmin(request);const settings=await readStreamingSettings(db());return json({...settings,transcriptionReady:!!runtime().OPENAI_API_KEY})}
 if(p==='admin/rewards'){requireAdmin(request);return json(await readRewardSettings({db:db()}))}
 if(p==='intelligence')return json(await getIntelligence({db:db(),env:runtime()}));
 if(p==='videos')return json(publicVideoSettings(await readVideoSettings(db())));
 if(p==='sources')return json({sources:(await setting<any[]>('sources',sourceCandidates)).filter(s=>s.approved===true).map(s=>({id:s.id,name:s.name,category:s.category}))});
 if(p==='admin/videos'){requireAdmin(request);return json(await readVideoSettings(db()))}
 if(p.startsWith('admin/distribution')){requireAdmin(request);const context=socialContext();if(p==='admin/distribution')return json(await socialStatus(context));if(p==='admin/distribution/connect'){const {url:authorizeUrl}=await beginXOAuth(context);return Response.redirect(authorizeUrl,302)}if(p==='admin/distribution/callback'){try{await completeXOAuth(context,{state:url.searchParams.get('state')||'',code:url.searchParams.get('code')||'',error:url.searchParams.get('error')||undefined});return page('X account connected.','<p>You can close this window and refresh your local publisher console.</p>')}catch(e){return page('X connection needs attention.','<p>'+escape((e as Error).message)+'</p><p>Close this window and reconnect from your local publisher console.</p>')}}if(p==='admin/distribution/export'){const edition=await getIntelligence({db:db(),env:runtime()}),format=url.searchParams.get('format'),brief={...edition.brief,date:edition.brief.localDate};const contents=format==='svg'?renderIntelligenceMap(edition):format==='html'?exportBriefHtml(brief):exportBriefText(brief);return new Response(contents,{headers:{'Content-Type':format==='svg'?'image/svg+xml; charset=utf-8':format==='html'?'text/html; charset=utf-8':'text/plain; charset=utf-8','Content-Disposition':'attachment; filename=jew-knows-osint.'+(format==='svg'?'svg':format==='html'?'html':'txt'),'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}}
 if(p==='edition')return json(await getEdition());
 if(p==='headlines'){const d=await getHeadlines();const donor=await setting<any[]>('donorHeadlines',[]);return json({...d,headlines:[...donor,...d.headlines].slice(0,30)})}
 if(p==='markets')return json(await getMarkets());
 if(p==='poll'){const poll=await getPoll();const browser=cookie(request,'current_voter');const voter=browser?await hash(browser):null;const vote=voter?await db().prepare('SELECT id FROM votes WHERE poll_id=? AND voter=?').bind(poll.id,voter).first():null;return json({poll,counts:await pollCounts(poll.id,poll.options.length),voted:!!vote})}
 if(p==='comments'){const articleId=clean(url.searchParams.get('articleId'),100);const result=await db().prepare("SELECT id,name,body as text,created_at as createdAt FROM comments WHERE article_id=? AND status='approved' ORDER BY created_at").bind(articleId).all();return json({comments:result.results})}
 if(p.startsWith('media/')){const id=p.slice(6);if(!/^[a-f0-9-]{36}\.webp$/.test(id))return json({error:'Not found'},404);const image=await runtime().BUCKET?.get(id);if(!image)return json({error:'Image not found'},404);return new Response(image.body,{headers:{'Content-Type':'image/webp','Cache-Control':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff'}})}
 if(p==='admin/export'){requireAdmin(request);return json({format:'jew-knows-settings',version:1,exportedAt:now(),sources:await setting('sources',sourceCandidates),ads:await setting('ads',defaultAds),adDensity:await setting('adDensity',3),marqueeOverride:await setting('marqueeOverride',''),videos:await readVideoSettings(db()),deals:await readDeals(db()),streaming:await readStreamingSettings(db()),rewards:await readRewardSettings({db:db()}),distribution:(await socialStatus(socialContext())).settings},200,{'Content-Disposition':'attachment; filename=jew-knows-settings.json'});}
 if(p==='admin'){requireAdmin(request);const [sources,ads,marqueeOverride,adDensity,items,subscribers,comments,logs]=await Promise.all([setting('sources',sourceCandidates),setting('ads',defaultAds),setting('marqueeOverride',''),setting('adDensity',3),getArticles(),db().prepare("SELECT COUNT(*) as count FROM subscribers WHERE status!='unsubscribed'").first<any>(),db().prepare("SELECT id,article_id as articleId,name,body as text,created_at as createdAt FROM comments WHERE status='pending' ORDER BY created_at DESC LIMIT 50").all(),db().prepare('SELECT id,message,created_at as createdAt FROM logs ORDER BY created_at DESC LIMIT 20').all()]);const e=runtime();return json({sources,sourceDirectory,ads:normalizeAdvertisers(ads),sourceHealth:await setting('sourceHealth',{}),adStats:await getAdvertisingStats(db(),ads),schedulingStatus:'Periodic background refresh is managed by your refresh task. Recent activity below shows completed runs.',marqueeOverride,adDensity,articleCount:items.length,subscriberCount:subscribers?.count||0,comments:comments.results,logs:logs.results,integrations:[{name:'RSS & headline reader',ready:true,description:'Google News headline discovery and individually approved donor feeds.'},{name:'Gold & silver',ready:true,description:'Keyless Gold API spot prices with a 30-second cache and source timestamps.'},{name:'AI writing & illustrations',ready:!!e.OPENAI_API_KEY,description:'Connect OpenAI API access for ongoing original summaries, unique images, and daily polls.'},{name:'Email briefs',ready:!!e.RESEND_API_KEY&&!!e.EMAIL_FROM,description:'Connect a verified sending domain and Resend key for confirmation emails and scheduled briefs.'},{name:'Stock market widgets',ready:true,description:'Free categorized TradingView stock feeds disclose exchange delays. Direct real-time equity quotes require an appropriately licensed connection.'},{name:'Live transcription',ready:!!e.OPENAI_API_KEY,description:'Viewer-consented tab audio uses 15-second AI caption segments when connected; provider CC is available where supported.'},{name:'Flight prices',ready:!!e.TRAVELPAYOUTS_TOKEN,description:'Travel-data credentials enable cached fare observations; Google Flights and Kayak searches work now.'},{name:'Local dining ratings',ready:!!e.GOOGLE_PLACES_API_KEY,description:'Google Places credentials show rating and rating count. Maps and Yelp searches work now.'}]})}
 if(p==='maintenance/status'){requireMaintenance(request);const lastResult=await setting('maintenanceLastResult',null);const sourceHealth=await setting('sourceHealth',{});const intelligence=await getIntelligence({db:db(),env:runtime()});const distribution=await socialStatus(socialContext());const logs=await db().prepare('SELECT message,created_at as createdAt FROM logs ORDER BY created_at DESC LIMIT 5').all();return json({lastResult,sourceHealth,brain:await setting('brainLastRefresh',null),intelligence:{status:intelligence.status,refreshedAt:intelligence.brief.refreshedAt,nextRefreshAt:intelligence.brief.nextRefreshAt,coverage:intelligence.coverage},distribution,logs:logs.results})}
 if(p==='subscriptions/confirm'){const token=url.searchParams.get('token')||'';const row=await db().prepare('SELECT id FROM subscribers WHERE token=?').bind(token).first();if(!row)return page('This link has expired.','<p>Set up your brief again to receive a new confirmation link.</p>');await db().prepare("UPDATE subscribers SET status='active' WHERE token=? AND status='pending'").bind(token).run();return page('Your brief is confirmed.','<p>Your selected edition will arrive on the days and at the time you chose.</p>')}
 if(p==='subscriptions/unsubscribe'||p==='subscriptions/manage'){const token=url.searchParams.get('token')||'';const s=await db().prepare('SELECT email,topics,days,time,timezone,status FROM subscribers WHERE token=?').bind(token).first<any>();if(!s)return page('This link has expired.','<p>Please use the link from your most recent email.</p>');if(p.endsWith('unsubscribe'))return page('Unsubscribe from your brief?','<p>You can rejoin whenever you like.</p><form method="POST" action="/api/subscriptions/unsubscribe"><input type="hidden" name="token" value="'+escape(token)+'"><button style="padding:14px 22px;background:#141517;border:0;color:white;font:inherit">Unsubscribe</button></form>');return page('Your edition, on your terms.','<p>'+escape(s.email)+'</p><p>'+escape(JSON.parse(s.topics).join(' · '))+'</p><p>'+escape(s.time+' · '+s.timezone)+'</p><p><a href="/brief">Update your brief preferences</a></p><form method="POST" action="/api/subscriptions/unsubscribe"><input type="hidden" name="token" value="'+escape(token)+'"><button style="padding:14px 22px;background:#141517;border:0;color:white;font:inherit">Unsubscribe</button></form>')}
 return json({error:'Not found'},404);
 }catch(e){console.error('News request failed',path(request),(e as Error).message);const msg=(e as Error).message,status=msg.includes('Sign in')?401:msg.includes('Publisher access')?403:msg.includes('five-digit')?400:msg.includes('wait before')?429:503;return json({error:path(request).startsWith('admin')?msg:readerError(msg,status)},status)}}
export async function POST(request:Request){try{const p=path(request);const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return json({error:'Request origin not allowed'},403);if(p==='subscriptions/unsubscribe'){const form=await request.formData();const token=String(form.get('token')||'');await db().prepare("UPDATE subscribers SET status='unsubscribed' WHERE token=?").bind(token).run();return page('You’re unsubscribed.','<p>Your brief has been paused. Thank you for reading Jew Knows.</p>')}
 if(p==='streaming/transcribe'){
  if(origin!==new URL(request.url).origin||request.headers.get('X-Broadcast-Consent')!=='tab-audio')return json({error:'Start captions from the Streaming page and consent to tab audio.'},403);
  const settings=await readStreamingSettings(db());if(!settings.transcriptionEnabled||!runtime().OPENAI_API_KEY)return json({error:'Live captions are temporarily unavailable. Use the broadcaster’s CC controls.'},503);
  if(+(request.headers.get('content-length')||0)>TRANSCRIPTION_MAX_BYTES)return json({error:'Audio segment exceeds 2 MB.'},413);
  await rateLimit(request,'live-transcription',300);
  const reader=request.body?.getReader();if(!reader)return json({error:'Supply a recorded audio segment.'},400);let bytes=0;const chunks:Uint8Array<ArrayBuffer>[]=[];
  try{while(true){const part=await reader.read();if(part.done)break;bytes+=part.value.byteLength;if(bytes>TRANSCRIPTION_MAX_BYTES){await reader.cancel();return json({error:'Audio segment exceeds 2 MB.'},413)}chunks.push(part.value as Uint8Array<ArrayBuffer>);}}finally{reader.releaseLock()}
  return json(await transcribeChunk(runtime().OPENAI_API_KEY,new Blob(chunks,{type:request.headers.get('content-type')||''})));
 }
 if(+(request.headers.get('content-length')||0)>512000)return json({error:'Request too large'},413);const raw=await request.text();if(raw.length>512000)return json({error:'Request too large'},413);const b:any=JSON.parse(raw);
 if(p==='rewards/start'){await rateLimit(request,'reward-start',120);return json(await startRewardSession({db:db()},b))}
 if(p==='rewards/progress'){await rateLimit(request,'reward-progress',2400);return json(await heartbeatRewardSession({db:db()},b))}
 if(p==='rewards/claim'){await rateLimit(request,'reward-claim',120);return json(await claimReward({db:db()},b))}
 if(p==='ads/serve'){await rateLimit(request,'ad-delivery',5000);return json({slots:await reserveAdSlots(db(),await setting('ads',defaultAds),b.count??1)});}
 if(p==='brain/refresh'){requireAdmin(request);if(request.headers.get('origin')!==new URL(request.url).origin)return json({error:'A same-origin request is required.'},403);const last=await setting<any>('brainLastRefresh',null);if(last?.at&&Date.now()-Date.parse(last.at)<5*60000)return json({skipped:true});return json(await maintenance());}
 if(p==='profile'){const key=await readerKey(request);if(request.headers.get('origin')!==new URL(request.url).origin)return json({error:'A same-origin request is required.'},403);return json(await saveProfile({db:db()},key,b));}
 if(p==='personal'){await rateLimit(request,'personal-brief',60);return json(await personalBrief({db:db()},b));}
 if(p==='maintenance'){requireMaintenance(request);return json(await maintenance())}
 if(p==='poll/vote'){await rateLimit(request,'vote',15);const poll=await getPoll();if(b.pollId!==poll.id||!Number.isInteger(b.option)||b.option<0||b.option>=poll.options.length)return json({error:'Select a valid option for Jew Knows poll.'},400);const browser=cookie(request,'current_voter')||crypto.randomUUID();const voter=await hash(browser);await db().batch([db().prepare('INSERT INTO polls (id,data,created_at) VALUES (?,?,?) ON CONFLICT(id) DO NOTHING').bind(poll.id,JSON.stringify(poll),now()),db().prepare('INSERT INTO votes (id,poll_id,voter,option,created_at) VALUES (?,?,?,?,?) ON CONFLICT(poll_id,voter) DO NOTHING').bind(crypto.randomUUID(),poll.id,voter,b.option,now())]);return json({counts:await pollCounts(poll.id,poll.options.length),voted:true},200,{'Set-Cookie':'current_voter='+browser+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=31536000'})}
 if(p==='comments'){await rateLimit(request,'comment',8);const articleId=clean(b.articleId,100),name=clean(b.name,60),text=String(b.text||'').trim().slice(0,2000);if(name.length<2||text.length<5)return json({error:'Add your name and a comment of at least five characters.'},400);const items=await getArticles();if(!items.some(a=>a.id===articleId))return json({error:'Story not found'},404);await db().prepare('INSERT INTO comments (id,article_id,name,body,status,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),articleId,name,text,'pending',now()).run();return json({status:'pending'})}
 if(p==='subscriptions'){await rateLimit(request,'subscribe',5);const email=String(b.email||'').trim().toLowerCase();const validTopics=Array.isArray(b.topics)?b.topics.filter((c:any)=>categories.slice(1).includes(c)):[];const days=Array.isArray(b.days)?[...new Set(b.days.filter((d:any)=>Number.isInteger(d)&&d>=0&&d<=6))]:[];if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254||!validTopics.length||!days.length||!/^([01]\d|2[0-3]):[0-5]\d$/.test(b.time)||b.consent!==true)return json({error:'Complete your email, topics, days, and consent.'},400);try{new Intl.DateTimeFormat('en-US',{timeZone:b.timezone})}catch{return json({error:'Choose a valid time zone.'},400)}const token=crypto.randomUUID()+crypto.randomUUID(),id=crypto.randomUUID();await db().prepare('INSERT INTO subscribers (id,email,topics,days,time,timezone,length,status,token,created_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET topics=excluded.topics,days=excluded.days,time=excluded.time,timezone=excluded.timezone,length=excluded.length,status=excluded.status,token=excluded.token').bind(id,email,JSON.stringify(validTopics),JSON.stringify(days),b.time,b.timezone,['essential','balanced','complete'].includes(b.length)?b.length:'balanced','pending',token,now()).run();const ready=!!runtime().RESEND_API_KEY&&!!runtime().EMAIL_FROM;if(ready){await sendEmail(email,'Confirm your personal edition',emailLayout('<h2 style="font-family:Georgia;font-weight:400">Your world. Your brief.</h2><p>Confirm that you requested this edition, then we’ll send the stories you chose on your schedule.</p><p><a href="'+runtime().SITE_ORIGIN+'/api/subscriptions/confirm?token='+token+'">Confirm my email</a></p>',token),'confirm-'+token);const saved=await db().prepare('SELECT id FROM subscribers WHERE email=?').bind(email).first<any>();if(saved)await db().prepare('INSERT INTO cache (key,data,updated_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').bind('confirmation:'+saved.id,token,Date.now()).run();}return json({saved:true,deliveryReady:ready})}
 if(p==='flights'){await rateLimit(request,'flights',20);const origin=String(b.origin||'').toUpperCase(),destination=String(b.destination||'').toUpperCase();if(!/^[A-Z]{3}$/.test(origin)||!/^[A-Z]{3}$/.test(destination)||!/^\d{4}-\d{2}-\d{2}$/.test(b.depart)||b.returns&&b.returns<b.depart)return json({error:'Choose valid airport codes and travel dates.'},400);const query='Flights from '+origin+' to '+destination+' on '+b.depart+(b.returns?' returning '+b.returns:' one way');const googleUrl='https://www.google.com/travel/flights?hl=en&q='+encodeURIComponent(query);const kayakUrl='https://www.kayak.com/flights/'+origin+'-'+destination+'/'+b.depart+(b.returns?'/'+b.returns:'')+'?sort=price_a';let deals:any[]=[];if(runtime().TRAVELPAYOUTS_TOKEN){try{const params=new URLSearchParams({origin,destination,departure_at:b.depart,currency:'usd',sorting:'price',direct:'false',limit:'10',token:runtime().TRAVELPAYOUTS_TOKEN!});if(b.returns)params.set('return_at',b.returns);const r=await fetch('https://api.travelpayouts.com/aviasales/v3/prices_for_dates?'+params,{signal:AbortSignal.timeout(15000)});const d:any=await r.json();if(r.ok&&d.success)deals=(d.data||[]).map((x:any)=>({...x,url:x.link?'https://www.aviasales.com'+x.link:googleUrl}));}catch{}}return json({googleUrl,kayakUrl,deals,currency:'USD',message:runtime().TRAVELPAYOUTS_TOKEN?'No cached fares for these dates. Compare current offers directly below.':'Open current search results for your selected route and dates. Fare estimates are currently unavailable here.'})}
 if(p==='food'){await rateLimit(request,'food',20);const city=clean(b.city,150),cuisine=clean(b.cuisine,50);const coords=Number.isFinite(b.latitude)&&Number.isFinite(b.longitude)&&Math.abs(b.latitude)<=90&&Math.abs(b.longitude)<=180;if(!city&&!coords)return json({error:'Enter a city or allow your location.'},400);const place=coords?b.latitude+','+b.longitude:city;const query=(cuisine&&cuisine!=='All cuisines'?cuisine+' ':'')+'restaurants near '+place;const mapsUrl='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(query);const yelpUrl='https://www.yelp.com/search?find_desc='+encodeURIComponent(cuisine==='All cuisines'?'Restaurants':cuisine+' restaurants')+'&find_loc='+encodeURIComponent(place);let places:any[]=[];if(runtime().GOOGLE_PLACES_API_KEY){try{const body=coords?{includedTypes:['restaurant'],maxResultCount:12,locationRestriction:{circle:{center:{latitude:b.latitude,longitude:b.longitude},radius:5000}}}:{textQuery:query,pageSize:12};const endpoint=coords?'searchNearby':'searchText';const r=await fetch('https://places.googleapis.com/v1/places:'+endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':runtime().GOOGLE_PLACES_API_KEY!,'X-Goog-FieldMask':'places.displayName,places.formattedAddress,places.rating,places.userRatingCount,places.googleMapsUri'},body:JSON.stringify(body),signal:AbortSignal.timeout(12000)});const d:any=await r.json();if(r.ok)places=(d.places||[]).map((p:any)=>({name:p.displayName?.text,address:p.formattedAddress,rating:p.rating,ratingCount:p.userRatingCount,url:p.googleMapsUri})).sort((a:any,b:any)=>(b.rating||0)-(a.rating||0));}catch{}}return json({mapsUrl,yelpUrl,places,message:places.length?'Ratings supplied by Google Maps. Verify current opening hours and availability.':'Compare top-rated local results on Google Maps or Yelp. Ratings are currently unavailable here.'})}
 if(p.startsWith('admin/')){requireAdmin(request);if(origin!==new URL(request.url).origin)return json({error:'A same-origin request is required.'},403);const action=p.slice(6);if(action==='brain'){if(request.headers.get('origin')!==new URL(request.url).origin)return json({error:'A same-origin request is required.'},403);return json(await saveBrainSettings({db:db()},b));}if(action==='forecast-resolution'){if(request.headers.get('origin')!==new URL(request.url).origin)return json({error:'A same-origin request is required.'},403);return json(await resolveForecast({db:db()},b,request.headers.get('oai-authenticated-user-id')||'owner'));}if(action==='deals')return json(await saveDeals(db(),b));if(action==='deals-preview'){await rateLimit(request,'deal-preview',120);return json(await previewDeal(b.url))}if(action==='streaming'){const settings=await saveStreamingSettings(db(),b);return json({...settings,transcriptionReady:!!runtime().OPENAI_API_KEY})}if(action==='rewards')return json(await saveRewardSettings({db:db()},b));if(action==='videos')return json(await saveVideoSettings(db(),b));if(action==='distribution')return json(await saveDistributionSettings(socialContext(),b));if(action==='distribution/client')return json(await saveXClient(socialContext(),b));if(action==='distribution/resolve')return json(await resolveXDelivery(socialContext(),b));if(action==='distribution/disconnect')return json(await disconnectX(socialContext()));if(action==='refresh')return json(await maintenance());if(action==='test-source'){
 const feedUrl=safeUrl(b.feedUrl);const entries=await fetchRSS(feedUrl);
 if(!entries.length)return json({valid:false,itemCount:0,error:'The feed contains no readable stories.'},422);
 const proof={valid:true,checkedAt:Date.now(),itemCount:entries.length};await saveSetting('feedVerified:'+feedUrl,proof);
 return json({...proof,sample:entries.slice(0,3).map(e=>({title:e.title,author:e.author,url:e.url})),hasFullText:entries.some((e:any)=>e.fullContentStatus==='available')});
 }
 if(action==='sources'){
 const sources=validateSources(b.sources);const previous=await setting<any[]>('sources',sourceCandidates);
 for(const source of sources.filter(s=>s.approved)){
  const unchanged=previous.some(s=>s.id===source.id&&s.feedUrl===source.feedUrl&&s.approved);
  const known=sourceDirectory.some(d=>d.feedUrl===source.feedUrl&&d.feedVerified);
  const proof=await setting<any>('feedVerified:'+source.feedUrl,null);
  if(!unchanged&&!known&&(!proof?.valid||Date.now()-proof.checkedAt>86400000))return json({error:source.name+': test this RSS feed before enabling it.'},400);
 }
 await saveSetting('sources',sources);await log('Donor source and reuse settings updated.');return json({saved:true,refresh:await maintenance()});
 }
 if(action==='ads'){
 const ads=normalizeAdvertisers(b.ads).map(a=>({...a,url:a.url?safeUrl(a.url):'',image:a.image?safeUrl(a.image):''}));
 if(!Number.isInteger(b.adDensity)||b.adDensity<2||b.adDensity>5)return json({error:'Select two to five banners.'},400);
 await db().batch([db().prepare('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('ads',JSON.stringify(ads)),db().prepare('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('adDensity',JSON.stringify(b.adDensity))]);
 await log('Site-wide advertiser percentages and creatives updated.');return json({saved:true});
 }
 if(action==='headlines'){await saveSetting('marqueeOverride',String(b.marqueeOverride||'').slice(0,3000));return json({saved:true})}if(action==='headline'){const url=safeUrl(b.url),title=clean(b.title,220);if(!title)return json({error:'Headline required'},400);const old=await setting<any[]>('manualHeadlines',[]);await saveSetting('manualHeadlines',[{title,url,publisher:'Editor-selected',publishedAt:now()},...old].slice(0,10));return json({saved:true})}if(action==='comments'){if(!['approved','rejected'].includes(b.status))return json({error:'Invalid moderation status'},400);await db().prepare('UPDATE comments SET status=? WHERE id=?').bind(b.status,clean(b.id,100)).run();return json({saved:true})}}
 return json({error:'Not found'},404);
 }catch(e){console.error('News write failed',path(request),(e as Error).message);const m=(e as Error).message,status=m.includes('Sign in')?401:m.includes('Publisher access')?403:m.includes('wait before')?429:400;return json({error:path(request).startsWith('admin/')?m:readerError(m,status)},status)}}
