import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import ts from 'typescript';

const root=new URL('../',import.meta.url),modules=new Map();
function load(name){if(modules.has(name))return modules.get(name);const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(new URL('lib/'+name+'.ts',root),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;new Function('require','module','exports',code)(n=>load(n.replace('./','')),module,module.exports);modules.set(name,module.exports);return module.exports}
const {searchArticles}=load('article-search');
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE stories(id TEXT,slug TEXT,source_url TEXT,data TEXT,published_at TEXT,status TEXT)');const db={prepare(query){let values=[];return {bind(...args){values=args;return this},async first(){return sql.prepare(query).get(...values)||null},async all(){return {results:sql.prepare(query).all(...values)}}}}};const insert=(n,patch={})=>{const a={id:String(n),slug:'story-'+n,title:'Archive report '+n,dek:'Source material',publisher:'Donor',author:'Author',category:'World',sourceUrl:'https://donor.example/'+n,image:'/test.webp',publishedAt:new Date(1720000000000+n*1000).toISOString(),paragraphs:['A complete source paragraph.'],...patch};sql.prepare('INSERT INTO stories VALUES(?,?,?,?,?,?)').run(a.id,a.slug,a.sourceUrl,JSON.stringify(a),a.publishedAt,patch.status||'published');return a};return {sql,db,insert}}
test('search finds older published stories by article body and author without returning full bodies',async()=>{const f=fixture();try{f.insert(0,{author:'Very Specific Author',paragraphs:['Rare intelligence signal.']});for(let n=1;n<125;n++)f.insert(n);f.insert(200,{title:'Rare intelligence signal',status:'held'});const r=await searchArticles(f.db,'rare signal');assert.equal(r.total,1);assert.equal(r.results[0].slug,'story-0');assert.equal('paragraphs' in r.results[0],false);assert.equal((await searchArticles(f.db,'Specific Author')).total,1)}finally{f.sql.close()}});
test('archive pagination is stable and does not repeat results',async()=>{const f=fixture();try{for(let n=0;n<45;n++)f.insert(n);const a=await searchArticles(f.db,'Archive report'),b=await searchArticles(f.db,'Archive report',2),c=await searchArticles(f.db,'Archive report',3);assert.deepEqual([a.results.length,b.results.length,c.results.length],[20,20,5]);assert.equal(a.hasMore,true);assert.equal(c.hasMore,false);assert.equal(new Set([...a.results,...b.results,...c.results].map(a=>a.id)).size,45)}finally{f.sql.close()}});
test('wildcard characters are literal and query text cannot modify SQL',async()=>{const f=fixture();try{f.insert(1,{title:'A 20% improvement'});f.insert(2,{title:'Everything else'});assert.equal((await searchArticles(f.db,'20%')).total,1);assert.equal((await searchArticles(f.db,'%')).total,1);assert.equal((await searchArticles(f.db,"' OR 1=1 --")).total,0);assert.equal((await searchArticles(f.db,'')).total,0)}finally{f.sql.close()}});
