import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
const root=fileURLToPath(new URL('../',import.meta.url)),modules=new Map();
function load(file){if(modules.has(file))return modules.get(file).exports;const module={exports:{}};modules.set(file,module);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;new Function('require','module','exports',code)(name=>load(path.resolve(path.dirname(file),name+'.ts')),module,module.exports);return module.exports}
const core=load(path.join(root,'lib/forecast-core.ts')),brain=load(path.join(root,'lib/forecast.ts'));
const at='2026-10-05T14:00:00.000Z',source={id:'one',name:'One Publisher',approved:true,feedUrl:'https://publisher.example/rss',category:'AI & Technology'};
const report=(changes={})=>({id:'report-a',title:'Artificial intelligence adoption expands',excerpt:'Organizations report new technology deployments.',description:'Organizations report new technology deployments.',sourceId:'one',sourceUrl:'https://publisher.example/article',url:'https://publisher.example/article',publisher:'One Publisher',author:'Original Author',publishedAt:'2026-10-05T13:00:00.000Z',category:'AI & Technology',assessment:'source-reported',...changes});
function fixture(){const sqlite=new DatabaseSync(':memory:');for(const name of fs.readdirSync(path.join(root,'drizzle')).filter(n=>n.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync(path.join(root,'drizzle',name),'utf8'));const writes=[];const db={prepare(sql){let values=[];return {bind(...v){values=v;return this},async first(){if(/^(INSERT|UPDATE|DELETE)/.test(sql))writes.push(sql);return sqlite.prepare(sql).get(...values)??null},async all(){return {results:sqlite.prepare(sql).all(...values)}},async run(){writes.push(sql);return {meta:{changes:Number(sqlite.prepare(sql).run(...values).changes)}}}}},async batch(statements){sqlite.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};const setting=(key,value)=>sqlite.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,JSON.stringify(value));const snapshot=(items,time=at)=>sqlite.prepare('INSERT INTO cache(key,data,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').run('osint-feed:one',JSON.stringify({sourceId:'one',collectedAt:time,items}),Date.parse(time));return {sqlite,db,writes,setting,snapshot}}
const question={id:'deployments',question:'Will the named operator announce a new deployment within the specified window?',topic:'technology',deadline:'2026-10-07T14:00:00.000Z',prior:.4,priorBasis:'Declared owner assumption; not an empirical base rate.',resolutionRule:'A dated official announcement naming the operator and deployment within the issued deadline window.',support:['adoption expands'],contrary:['deployment cancelled'],enabled:true};
test('Gamma–Poisson prediction integrates the uncertain rate and increases with the same-event horizon',()=>{assert.ok(Math.abs(core.coverageProbability(0,0,24)-(1-Math.sqrt(.5)))<1e-12);assert.equal(core.coverageProbability(5,24,0),0);assert.ok(core.coverageProbability(5,24,168)>core.coverageProbability(5,24,24));for(const args of [[-1,24,24],[1,-1,24],[1,24,Infinity],[NaN,24,24]])assert.throws(()=>core.coverageProbability(...args));});
test('collection completeness rejects explicit outages, changed source rosters, long gaps and unobserved deadlines',()=>{const run=(minute,complete=1,fingerprint='a')=>({at:new Date(Date.parse(at)+minute*60000).toISOString(),complete,fingerprint}),end=new Date(Date.parse(at)+60*60000).toISOString();assert.equal(core.completeCoverage([run(0),run(30),run(60)],at,end,'a'),true);assert.equal(core.completeCoverage([run(0),run(20,0),run(30),run(60)],at,end,'a'),false);assert.equal(core.completeCoverage([run(0),run(20,1,'b'),run(30),run(60)],at,end,'a'),false);assert.equal(core.completeCoverage([run(0),run(30)],at,end,'a'),false);assert.equal(core.completeCoverage([run(0),run(120)],at,new Date(Date.parse(at)+120*60000).toISOString(),'a'),false)});
test('syndicated copies, repeated URLs and negated keywords cannot multiply directional evidence',()=>{const q={...question,support:['raise rates']},items=[report({title:'Operator will raise rates',publisher:'Reuters'}),report({id:'other',sourceUrl:'https://other.example/copy',title:'Reuters says operator will raise rates',publisher:'Second Publisher'})];const one=core.bayesianQuestion(q,items,core.DEFAULT_BRAIN_SETTINGS,at);assert.equal(one.evidence.length,1);assert.equal(core.bayesianQuestion(q,[report({title:'Operator will not raise rates',excerpt:''})],core.DEFAULT_BRAIN_SETTINGS,at).probability,q.prior);assert.equal(core.independentEvidence([report(),report({sourceUrl:'https://publisher.example/article?utm_source=copy'})]).length,1)});
test('zero approved evidence yields no network estimates, no fabricated observations and no risk number',async()=>{const f=fixture();try{await brain.refreshBrain({db:f.db,now:at,complete:true});const d=await brain.getBrain({db:f.db,now:at});assert.equal(d.status,'waiting');assert.equal(d.pressure.value,null);assert.deepEqual(d.forecasts,[]);assert.equal(f.sqlite.prepare('SELECT COUNT(*) as n FROM brain_observations').get().n,0);assert.equal(f.sqlite.prepare('SELECT COUNT(*) as n FROM forecast_events').get().n,0);assert.equal(d.scores.coverage.brier,null)}finally{f.sqlite.close()}});
test('world assumptions produce append-only revisions without resetting the question or issued probability',async()=>{const f=fixture();try{f.setting('sources',[source]);f.setting('brainSettings',{...core.DEFAULT_BRAIN_SETTINGS,questions:[question]});f.snapshot([report()]);await brain.refreshBrain({db:f.db,now:at});const first=(await brain.getLedger({db:f.db,now:at})).events[0];assert.equal(first.kind,'world');assert.ok(first.initialProbability>.4);f.setting('brainSettings',{...core.DEFAULT_BRAIN_SETTINGS,halfLifeHours:72,questions:[{...question,prior:.3}]});await brain.refreshBrain({db:f.db,now:'2026-10-05T14:30:00.000Z'});const details=await brain.getLedger({db:f.db,now:at},first.id);assert.equal(details.events.length,1);assert.equal(details.events[0].initialProbability,first.initialProbability);assert.equal(details.events[0].deadline,first.deadline);assert.equal(details.revisions.length,2);assert.notEqual(details.revisions[1].probability,first.initialProbability);await brain.refreshBrain({db:f.db,now:'2026-10-06T15:00:00.000Z'});const current=await brain.getBrain({db:f.db,now:'2026-10-06T15:00:00.000Z'});assert.ok(Math.abs(current.forecasts[0].currentProbability-.3)<1e-12);assert.equal(current.forecasts[0].revision.status,'insufficient-evidence')}finally{f.sqlite.close()}});
test('deadline expiry is unknown and owner verification preserves an auditable correction history',async()=>{const f=fixture();try{f.setting('sources',[source]);f.setting('brainSettings',{...core.DEFAULT_BRAIN_SETTINGS,questions:[question]});f.snapshot([report()]);await brain.refreshBrain({db:f.db,now:at});const id=(await brain.getLedger({db:f.db,now:at})).events[0].id;await brain.refreshBrain({db:f.db,now:'2026-10-08T14:00:00.000Z'});let detail=await brain.getLedger({db:f.db,now:at},id);assert.equal(detail.events[0].status,'UNKNOWN');assert.equal(detail.scores.world.count,0);await assert.rejects(brain.resolveForecast({db:f.db,now:at},{eventId:id,outcome:'FALSE',url:'https://publisher.example/proof',reason:'A complete official record establishes no qualifying event.'},'owner'),/before its deadline/);await brain.resolveForecast({db:f.db,now:'2026-10-08T14:00:00.000Z'},{eventId:id,outcome:'TRUE',eventOccurredAt:'2026-10-06T13:00:00.000Z',url:'https://publisher.example/proof',reason:'The official dated announcement establishes the exact frozen event.'},'owner');detail=await brain.getLedger({db:f.db,now:at},id);assert.equal(detail.events[0].status,'TRUE');assert.equal(detail.resolutionHistory.length,2);assert.equal(detail.scores.world.count,1);f.setting('sources',[{...source,approved:false}]);detail=await brain.getLedger({db:f.db,now:at},id);assert.deepEqual(detail.events[0].evidence,[]);assert.equal(detail.events[0].resolution.url,'');assert.equal(detail.events[0].sourceApproval,'changed')}finally{f.sqlite.close()}});
test('old exact ledger lookup and scoring are independent of display limits; public reads never write',async()=>{const f=fixture();try{for(let i=0;i<650;i++){const event={id:'old-'+i,kind:'world',question:'Measurable archived question '+i,topic:'technology',issuedAt:new Date(Date.parse(at)+i*1000).toISOString(),deadline:'2026-10-07T14:00:00.000Z',initialProbability:.4,rawProbability:.4,prior:.3,modelVersion:core.BRAIN_VERSION,horizon:'custom',sourceIds:['one'],fingerprint:'a',resolutionRule:'Frozen event rule.',assumptions:'Declared prior.',evidence:[]};f.sqlite.prepare('INSERT INTO forecast_events(id,issued_at,deadline,kind,probability,data) VALUES(?,?,?,?,?,?)').run(event.id,event.issuedAt,event.deadline,event.kind,.4,JSON.stringify(event))}f.writes.length=0;const exact=await brain.getLedger({db:f.db,now:at},'old-0');assert.equal(exact.events[0].id,'old-0');assert.equal((await brain.getLedger({db:f.db,now:at})).events.length,200);await brain.getBrain({db:f.db,now:at});assert.deepEqual(f.writes,[])}finally{f.sqlite.close()}});
test('calibration remains bounded and Brier scores measure probability error, not an accuracy percentage',()=>{const fit=core.fitCalibrationIntercept(Array.from({length:50},(_,i)=>({raw:.8,outcome:i<15?1:0})));assert.ok(fit>=-.35&&fit<=.35&&fit<0);assert.equal(core.fitCalibrationIntercept([{raw:.5,outcome:1}]),0);const score=core.brier([{probability:.8,outcome:1,prior:.5},{probability:.2,outcome:0,prior:.5}]);assert.ok(Math.abs(score.brier-.04)<1e-12);assert.equal(score.baseline,.25);assert.equal(score.count,2);assert.equal(core.brier([]).brier,null)});
test('withdrawing contributing evidence suppresses live estimates without erasing history or writing on read',async()=>{
 const f=fixture();try{
  const unrelated={...source,id:'two',name:'Other Publisher',feedUrl:'https://other.example/rss'};
  f.setting('sources',[source,unrelated]);f.setting('brainSettings',{...core.DEFAULT_BRAIN_SETTINGS,questions:[question]});f.snapshot([report()]);
  await brain.refreshBrain({db:f.db,now:at});const original=(await brain.getBrain({db:f.db,now:at})).forecasts[0];assert.ok(original);
  f.setting('sources',[source,{...unrelated,approved:false}]);f.writes.length=0;
  assert.equal((await brain.getBrain({db:f.db,now:at})).forecasts[0].id,original.id);
  f.setting('sources',[{...source,approved:false},unrelated]);
  assert.equal((await brain.getBrain({db:f.db,now:at})).forecasts.length,0);
  assert.equal((await brain.getLedger({db:f.db,now:at},original.id)).events[0].initialProbability,original.initialProbability);
  assert.deepEqual(f.writes,[]);
 }finally{f.sqlite.close()}
});
