import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
const root=fileURLToPath(new URL('../',import.meta.url)),cache=new Map();
function load(file){if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;new Function('require','module','exports',code)(name=>load(path.resolve(path.dirname(file),name+'.ts')),module,module.exports);return module.exports}
const {localIntelligence}=load(path.join(root,'lib/local-intelligence.ts'));
const at=Date.parse('2026-10-05T14:00:00Z');
function fixture(){const sqlite=new DatabaseSync(':memory:');sqlite.exec('CREATE TABLE cache(key TEXT PRIMARY KEY,data TEXT,updated_at INTEGER)');const db={prepare(sql){let args=[];return {bind(...v){args=v;return this},async first(){return sqlite.prepare(sql).get(...args)??null},async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}}}}}};return {sqlite,db}}
const zipData={places:[{'place name':'Beverly Hills',state:'California','state abbreviation':'CA',latitude:'34.0901',longitude:'-118.4065'}]};
test('ZIP context stays separate from model evidence and labels GDELT time as indexed',async()=>{const f=fixture(),old=globalThis.fetch,calls=[];globalThis.fetch=async(url,options)=>{calls.push({url:String(url),options});if(String(url).includes('zippopotam'))return Response.json(zipData);if(String(url).includes('weather.gov'))return Response.json({features:[]});return Response.json({articles:[{url:'https://publisher.example/local',title:'City-linked coverage',seendate:'20261005T130000Z'}]})};try{const d=await localIntelligence({db:f.db,now:at},'90210');assert.equal(d.status,'ready');assert.equal(d.place.city,'Beverly Hills');assert.equal(d.news.value[0].indexedAt,'2026-10-05T13:00:00Z');assert.equal('publishedAt' in d.news.value[0],false);assert.match(d.scope,/representative point/);assert.ok(calls.every(c=>['api.zippopotam.us','api.weather.gov','api.gdeltproject.org'].includes(new URL(c.url).hostname)));assert.ok(calls.every(c=>c.options.redirect==='manual'));assert.ok(calls.every(c=>c.options.headers['User-Agent']));assert.ok(!calls.some(c=>c.url.includes('publisher.example')))}finally{globalThis.fetch=old;f.sqlite.close()}});
test('a non-JSON throttle response is unavailable rather than a claim of no news',async()=>{const f=fixture(),old=globalThis.fetch;globalThis.fetch=async url=>String(url).includes('zippopotam')?Response.json(zipData):String(url).includes('weather.gov')?Response.json({features:[]}):new Response('Please limit requests to one every 5 seconds.');try{const d=await localIntelligence({db:f.db,now:at},'90210');assert.equal(d.status,'partial');assert.equal(d.news.value,null);assert.match(d.news.error,/unavailable|rate limited/)}finally{globalThis.fetch=old;f.sqlite.close()}});
test('stale weather warnings are retained as history and never become current guidance during an outage',async()=>{const f=fixture(),old=globalThis.fetch;f.sqlite.prepare('INSERT INTO cache(key,data,updated_at) VALUES(?,?,?)').run('local-weather:90210',JSON.stringify({value:[{event:'Expired storm warning',expires:'2026-10-05T12:00:00Z'}],retrievedAt:'2026-10-05T11:00:00Z'}),at-3*3600000);globalThis.fetch=async url=>String(url).includes('zippopotam')?Response.json(zipData):String(url).includes('weather.gov')?new Response('Unavailable',{status:503}):Response.json({articles:[]});try{const d=await localIntelligence({db:f.db,now:at},'90210');assert.equal(d.weather.stale,true);assert.equal(d.pathways[0].title,'Weather updates are temporarily unavailable');assert.ok(!JSON.stringify(d.pathways).includes('Expired storm warning'))}finally{globalThis.fetch=old;f.sqlite.close()}});
test('invalid ZIP input is rejected before any provider request',async()=>{const f=fixture(),old=globalThis.fetch;globalThis.fetch=async()=>{throw Error('Unexpected network call')};try{for(const zip of ['9021','902100','../admin','abcde'])await assert.rejects(localIntelligence({db:f.db,now:at},zip),/five-digit/)}finally{globalThis.fetch=old;f.sqlite.close()}});

test('edge-compatible manual redirects reject changed hosts without making a second request',async()=>{const f=fixture(),old=globalThis.fetch,calls=[];globalThis.fetch=async(url,options)=>{assert.equal(options.redirect,'manual');calls.push(String(url));return new Response('',{status:302,headers:{Location:'https://other.example/zip'}})};try{const d=await localIntelligence({db:f.db,now:at},'90210');assert.equal(d.status,'unavailable');assert.match(d.errors[0],/temporarily unavailable/);assert.deepEqual(calls,['https://api.zippopotam.us/us/90210'])}finally{globalThis.fetch=old;f.sqlite.close()}});

 test('missing ZIP is distinct from an outage and is not retried within backoff',async()=>{const f=fixture(),old=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return new Response('',{status:404})};try{const d=await localIntelligence({db:f.db,now:at},'00000');assert.equal(d.status,'not-found');assert.equal((await localIntelligence({db:f.db,now:at+1000},'00000')).status,'not-found');assert.equal(calls,1)}finally{globalThis.fetch=old;f.sqlite.close()}});
 test('outage backoff keeps earlier local coverage with its original timestamp',async()=>{const f=fixture(),old=globalThis.fetch;f.sqlite.prepare('INSERT INTO cache(key,data,updated_at) VALUES(?,?,?)').run('local-news:beverly hills:CA',JSON.stringify({value:[{title:'Earlier local report',url:'https://publisher.example/local',indexedAt:'2026-10-05T10:00:00Z'}],retrievedAt:'2026-10-05T11:00:00Z'}),at-3*3600000);let newsCalls=0;globalThis.fetch=async url=>String(url).includes('zippopotam')?Response.json(zipData):String(url).includes('weather.gov')?Response.json({features:[]}):(newsCalls++,new Response('Unavailable',{status:503}));try{const d=await localIntelligence({db:f.db,now:at},'90210');assert.equal(d.news.stale,true);assert.equal(d.news.retrievedAt,'2026-10-05T11:00:00Z');assert.equal((await localIntelligence({db:f.db,now:at+1000},'90210')).news.value[0].title,'Earlier local report');assert.equal(newsCalls,1)}finally{globalThis.fetch=old;f.sqlite.close()}});
