'use client';
import {useEffect,useRef,useState} from 'react';
import {Headphones,Play,Pause,Square} from 'lucide-react';

/** Reads source text passed as data. Advertisements are never part of this input. */
export function ArticleListen({title,paragraphs,complete}:{title:string;paragraphs:string[];complete?:boolean}){
 const [supported,setSupported]=useState(false),[playing,setPlaying]=useState(false),[paused,setPaused]=useState(false),[progress,setProgress]=useState(0),[rate,setRate]=useState(1),[error,setError]=useState('');
 const generation=useRef(0),current=useRef<SpeechSynthesisUtterance|null>(null),rateRef=useRef(rate);rateRef.current=rate;
 const text=[title,...paragraphs].join('\n\n');
 useEffect(()=>{setSupported('speechSynthesis' in window&&'SpeechSynthesisUtterance' in window);return()=>{generation.current++;window.speechSynthesis?.cancel()}},[title]);
 function stop(){generation.current++;current.current=null;window.speechSynthesis.cancel();setPlaying(false);setPaused(false);setProgress(0)}
 function start(){window.speechSynthesis.cancel();const session=++generation.current;const sentences=text.match(/[^.!?\n]+[.!?]?|\n/g)||[text];const chunks=sentences.flatMap(s=>{const words=s.trim().split(/\s+/),out:string[]=[];let line='';for(const word of words){if(line.length+word.length>230){out.push(line);line=''}line+=(line?' ':'')+word}if(line.trim())out.push(line);return out}).filter(Boolean);let index=0;setPlaying(true);setPaused(false);setProgress(0);setError('');
  const next=()=>{if(session!==generation.current)return;if(index>=chunks.length){setPlaying(false);setProgress(100);current.current=null;return}const utterance=new SpeechSynthesisUtterance(chunks[index]);utterance.lang='en-US';utterance.rate=rateRef.current;const voices=window.speechSynthesis.getVoices();utterance.voice=voices.find(v=>v.lang==='en-US'&&v.localService)||voices.find(v=>v.lang.startsWith('en'))||null;utterance.onend=()=>{if(session!==generation.current)return;index++;setProgress(Math.round(index/chunks.length*100));next()};utterance.onerror=e=>{if(session!==generation.current||e.error==='canceled'||e.error==='interrupted')return;setPlaying(false);setError('Audio is unavailable in this browser. Try another voice-enabled browser.')};current.current=utterance;window.speechSynthesis.speak(utterance)};next();
 }
 function toggle(){if(!playing){start();return}if(paused){window.speechSynthesis.resume();setPaused(false)}else{window.speechSynthesis.pause();setPaused(true)}}
 return <section className="article-listen" aria-label="Article audio"><div className="listen-title"><Headphones size={21}/><div><strong>Listen to {complete?'the article':'this story'}</strong><span>Article text only · No advertisements · Device voice</span></div></div><div className="listen-controls"><button className="button dark" onClick={toggle} disabled={!supported}>{playing&&!paused?<Pause size={15}/>:<Play size={15}/>} {playing?(paused?'Resume':'Pause'):'Listen to article'}</button>{playing&&<button className="icon-button" onClick={stop} aria-label="Stop reading"><Square size={15}/></button>}<label><span className="sr-only">Reading speed</span><select aria-label="Reading speed" value={rate} onChange={e=>setRate(Number(e.target.value))}>{[.8,1,1.2,1.5,1.8].map(v=><option key={v} value={v}>{v}×</option>)}</select></label></div>{(playing||progress===100)&&<div className="listen-progress" role="progressbar" aria-label="Article listening progress" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><span style={{width:progress+'%'}}/></div>}{error&&<p role="status">{error}</p>}{!supported&&<p className="listen-unavailable">Audio requires a browser with text-to-speech support.</p>}</section>
}
