'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Search,ArrowUpRight,ArrowLeft,ArrowRight,Loader2,X} from 'lucide-react';
import type {SearchResult} from '@/lib/article-search';

export function ArticleSearchBar(){return <form role="search" action="/search" className="article-search-bar"><Search size={17} aria-hidden="true"/><input aria-label="Search articles" name="q" type="search" placeholder="Search stories, sources, ideas…" maxLength={160}/><button type="submit" aria-label="Find articles"><ArrowUpRight size={17}/></button></form>}

export function ArticleSearchPage(){
 const [query,setQuery]=useState(''),[submitted,setSubmitted]=useState(''),[page,setPage]=useState(1),[results,setResults]=useState<SearchResult[]>([]),[total,setTotal]=useState(0),[hasMore,setHasMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const p=new URLSearchParams(location.search),q=(p.get('q')||'').slice(0,160);setQuery(q);setSubmitted(q);setPage(Math.max(1,Number(p.get('page'))||1))},[]);
 useEffect(()=>{if(!submitted.trim()){setResults([]);setTotal(0);return}const controller=new AbortController();setBusy(true);setError('');fetch('/api/search?'+new URLSearchParams({q:submitted,page:String(page)}),{signal:controller.signal}).then(async r=>{const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Search is temporarily unavailable.');setResults(d.results);setTotal(d.total);setHasMore(d.hasMore)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort()},[submitted,page]);
 function go(q:string,p=1){setSubmitted(q.trim());setPage(p);const url=new URL(location.href);url.search=new URLSearchParams({q:q.trim(),...(p>1?{page:String(p)}:{})}).toString();history.replaceState(null,'',url)}
 function submit(event:FormEvent){event.preventDefault();go(query)}
 return <div className="container search-page"><div className="page-heading"><span className="eyebrow accent">FOLLOW YOUR CURIOSITY</span><h1>Find the signal<span>.</span></h1><p>Search reporting, original authors, publishers, and topics.</p></div><form className="search-page-form" onSubmit={submit} role="search"><Search size={22}/><input aria-label="Search all published articles" autoFocus type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="What are you looking for?" maxLength={160}/>{query&&<button className="icon-button" type="button" aria-label="Clear search" onClick={()=>setQuery('')}><X size={18}/></button>}<button className="button dark" disabled={busy||!query.trim()}>Search</button></form><div className="search-results-status" role="status">{busy?<><Loader2 size={15} className="spin"/>Searching the archive…</>:error|| (submitted?`${total} ${total===1?'story':'stories'} for “${submitted}”`:'Every source. One search.')}</div>{!busy&&!error&&submitted&&results.length===0&&<div className="empty-state"><Search size={30}/><h2>No match yet.</h2><p>Try a broader topic, a company name, or a publisher.</p></div>}<div className="search-results">{results.map(a=><a className="search-result" href={'/article/'+a.slug} key={a.id}><div className="search-result-image"><img src={a.image} alt={a.imageLabel||'Editorial illustration'} loading="lazy"/></div><div><span className="eyebrow accent">{a.category}</span><h2>{a.title}</h2><p>{a.dek}</p><div className="story-meta"><span>{a.publisher}</span><span>{a.author}</span><time dateTime={a.publishedAt}>{new Date(a.publishedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</time></div></div><ArrowUpRight size={20}/></a>)}</div>{total>20&&<nav className="search-pagination" aria-label="Search result pages"><button className="button outline" disabled={page===1||busy} onClick={()=>go(submitted,page-1)}><ArrowLeft size={16}/>Previous</button><span>Page {page}</span><button className="button outline" disabled={!hasMore||busy} onClick={()=>go(submitted,page+1)}>Next<ArrowRight size={16}/></button></nav>}</div>
}
