import {buildIntelligence,publicIntelligenceUrl,type IntelligenceItem,type IntelligenceSource,type IntelligenceFeedSnapshot} from './intelligence-core';
import {BRAIN_VERSION,DEFAULT_BRAIN_SETTINGS,TOPICS,HORIZONS,bayesianQuestion,coverageProbability,calibrate,fitCalibrationIntercept,completeCoverage,independentEvidence,topicsFor,newsPressure,personalPathways,contextExposures,validateBrainSettings,validateProfile,digest,brier,type BrainSettings} from './forecast-core';

type Adapter={db:D1Database;now?:string|number;complete?:boolean};
type Forecast={id:string;kind:'coverage'|'world';question:string;topic:string;issuedAt:string;deadline:string;initialProbability:number;rawProbability:number;prior:number;modelVersion:string;horizon:string;sourceIds:string[];fingerprint:string;resolutionRule:string;assumptions:string;definition?:unknown;evidence:IntelligenceItem[]};
type Resolution={outcome:'TRUE'|'FALSE'|'UNKNOWN';eventOccurredAt:string|null;sourceId?:string;observedAt:string;verifiedAt:string;url:string;reason:string;reviewer:string};
const stamp=(a:Adapter)=>new Date(a.now??Date.now()).toISOString();
async function setting<T>(a:Adapter,key:string,fallback:T):Promise<T>{const row=await a.db.prepare('SELECT value FROM settings WHERE key=?').bind(key).first<{value:string}>();try{return row?JSON.parse(row.value):fallback}catch{return fallback}}
async function save(a:Adapter,key:string,value:unknown){await a.db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,JSON.stringify(value)).run()}
const decode=(rows:{data:string}[])=>rows.flatMap(row=>{try{return [JSON.parse(row.data)]}catch{return []}});
export async function readBrainSettings(a:Adapter){return setting<BrainSettings>(a,'brainSettings',DEFAULT_BRAIN_SETTINGS)}
export async function saveBrainSettings(a:Adapter,value:unknown){const settings=validateBrainSettings(value);await save(a,'brainSettings',settings);return settings}
async function evidence(a:Adapter){
 const sources=await setting<IntelligenceSource[]>(a,'sources',[]),at=stamp(a);
 const [stored,snapshots]=await Promise.all([a.db.prepare("SELECT data FROM stories WHERE status='published' AND published_at>=? ORDER BY published_at DESC LIMIT 800").bind(new Date(Date.parse(at)-86400000).toISOString()).all<{data:string}>(),a.db.prepare('SELECT data FROM cache WHERE key LIKE ? ORDER BY updated_at DESC LIMIT 200').bind('osint-feed:%').all<{data:string}>()]);
 const edition=buildIntelligence({sources,articles:decode(stored.results),feedSnapshots:decode(snapshots.results) as IntelligenceFeedSnapshot[],now:at,maxItems:600});
 const items=independentEvidence(edition.brief.items),sourceIds=sources.filter(s=>s.approved===true).map(s=>s.id).sort(),fingerprint=digest(JSON.stringify(sources.filter(s=>s.approved===true).map((s:any)=>({id:s.id,feedUrl:s.feedUrl??'',mode:s.mode??''})).sort((a,b)=>a.id.localeCompare(b.id))));
 return {items,sources,sourceIds,fingerprint,coverage:edition.coverage,collectedAt:decode(snapshots.results).filter(s=>sourceIds.includes(s.sourceId)).map(s=>s.collectedAt).filter(t=>Number.isFinite(Date.parse(t))&&Date.parse(t)<=Date.parse(at)).sort().at(-1)??null};
}
async function eventRows(a:Adapter,mode:'active'|'due'|'learning'|'history'='active',eventId?:string,page=1){
 let sql='SELECT e.data FROM forecast_events e',args:unknown[]=[];
 if(eventId){sql+=' WHERE e.id=?';args=[eventId]}
 else if(mode==='active'){sql+=" WHERE e.deadline>? AND NOT EXISTS(SELECT 1 FROM forecast_resolutions r WHERE r.event_id=e.id AND r.outcome IN ('TRUE','FALSE') AND r.rowid=(SELECT rr.rowid FROM forecast_resolutions rr WHERE rr.event_id=e.id ORDER BY rr.verified_at DESC,rr.rowid DESC LIMIT 1))";args=[stamp(a)]}
 else if(mode==='due'){sql+=" WHERE e.deadline<=? AND (NOT EXISTS(SELECT 1 FROM forecast_resolutions r WHERE r.event_id=e.id) OR (e.kind='coverage' AND e.deadline>=? AND (SELECT r.outcome FROM forecast_resolutions r WHERE r.event_id=e.id ORDER BY r.verified_at DESC,r.rowid DESC LIMIT 1)='UNKNOWN'))";args=[stamp(a),new Date(Date.parse(stamp(a))-3600000).toISOString()]}
 else if(mode==='learning'){sql+=" WHERE e.kind='coverage' AND json_extract(e.data,'$.horizon')='day' AND e.issued_at>? AND (SELECT r.outcome FROM forecast_resolutions r WHERE r.event_id=e.id ORDER BY r.verified_at DESC,r.rowid DESC LIMIT 1) IN ('TRUE','FALSE')";args=[await setting(a,'brainLearningAfter','')]}
 sql+=' ORDER BY e.issued_at DESC';if(mode==='history'&&!eventId){sql+=' LIMIT 200 OFFSET ?';args.push((page-1)*200)}
 return decode((await a.db.prepare(sql).bind(...args).all<{data:string}>()).results) as Forecast[];
}
async function resolutions(a:Adapter){const rows=await a.db.prepare('SELECT r.event_id,r.data FROM forecast_resolutions r WHERE r.rowid=(SELECT rr.rowid FROM forecast_resolutions rr WHERE rr.event_id=r.event_id ORDER BY rr.verified_at DESC,rr.rowid DESC LIMIT 1)').all<{event_id:string;data:string}>();const map=new Map<string,Resolution>();for(const row of rows.results){try{map.set(row.event_id,JSON.parse(row.data))}catch{}}return map}
async function latestRevisions(a:Adapter){const rows=await a.db.prepare('SELECT r.event_id,r.data FROM forecast_revisions r WHERE r.rowid=(SELECT rr.rowid FROM forecast_revisions rr WHERE rr.event_id=r.event_id ORDER BY rr.created_at DESC,rr.rowid DESC LIMIT 1) AND EXISTS(SELECT 1 FROM forecast_events e WHERE e.id=r.event_id AND e.deadline>?)').bind(stamp(a)).all<{event_id:string;data:string}>();const map=new Map<string,any>();for(const row of rows.results){try{map.set(row.event_id,JSON.parse(row.data))}catch{}}return map}
async function insertResolution(a:Adapter,eventId:string,resolution:Resolution){await a.db.prepare('INSERT INTO forecast_resolutions(id,event_id,outcome,verified_at,data) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),eventId,resolution.outcome,resolution.verifiedAt,JSON.stringify(resolution)).run()}
export async function resolveForecast(a:Adapter,input:any,reviewer:string){
 const row=await a.db.prepare('SELECT data FROM forecast_events WHERE id=?').bind(String(input.eventId)).first<{data:string}>();if(!row)throw Error('Forecast not found.');const event:Forecast=JSON.parse(row.data),at=stamp(a),outcome=input.outcome as Resolution['outcome'];if(!['TRUE','FALSE','UNKNOWN'].includes(outcome))throw Error('Choose TRUE, FALSE or UNKNOWN.');const reason=String(input.reason??'').trim().slice(0,1800),url=publicIntelligenceUrl(input.url),eventOccurredAt=input.eventOccurredAt?new Date(input.eventOccurredAt).toISOString():null;if(reason.length<30||!url)throw Error('A resolution requires an evidence link and a rationale of at least thirty characters.');if(eventOccurredAt&&Date.parse(eventOccurredAt)>Date.parse(at))throw Error('The event time cannot be in the future.');if(outcome==='TRUE'&&(!eventOccurredAt||eventOccurredAt<event.issuedAt||eventOccurredAt>event.deadline))throw Error('TRUE requires an event time within the frozen forecast window.');if(outcome==='FALSE'&&at<event.deadline)throw Error('A forecast cannot be marked FALSE before its deadline.');const sourceId=event.evidence.find(i=>new URL(i.sourceUrl).hostname===new URL(url).hostname)?.sourceId;const resolution:Resolution={outcome,sourceId,eventOccurredAt,observedAt:at,verifiedAt:at,url,reason,reviewer:'owner:'+await strongHash(reviewer)};await insertResolution(a,event.id,resolution);return {saved:true,resolution};
}
async function scoring(a:Adapter,_events?:Forecast[],_resolved?:Map<string,Resolution>){
 const rows=(await a.db.prepare("SELECT e.kind,e.probability,json_extract(e.data,'$.prior') as prior,r.outcome FROM forecast_events e JOIN forecast_resolutions r ON r.event_id=e.id AND r.rowid=(SELECT rr.rowid FROM forecast_resolutions rr WHERE rr.event_id=e.id ORDER BY rr.verified_at DESC,rr.rowid DESC LIMIT 1) WHERE r.outcome IN ('TRUE','FALSE')").all<{kind:string;probability:number;prior:number;outcome:string}>()).results;
 const scored=(kind:string)=>brier(rows.filter(r=>r.kind===kind).map(r=>({...r,outcome:r.outcome==='TRUE'?1:0})));
 const counts=await a.db.prepare("SELECT SUM(CASE WHEN (SELECT r.outcome FROM forecast_resolutions r WHERE r.event_id=e.id ORDER BY r.verified_at DESC,r.rowid DESC LIMIT 1)='UNKNOWN' THEN 1 ELSE 0 END) as unknown,SUM(CASE WHEN NOT EXISTS(SELECT 1 FROM forecast_resolutions r WHERE r.event_id=e.id) THEN 1 ELSE 0 END) as pending FROM forecast_events e").first<{unknown:number;pending:number}>();
 return {coverage:scored('coverage'),world:scored('world'),unknown:counts?.unknown??0,pending:counts?.pending??0,model:await setting<any>(a,'brainActiveModel',{id:BRAIN_VERSION,intercept:0}),learning:await setting(a,'brainLearning',{status:'Collecting verified outcomes',required:50,collected:0})};
}
/** A frozen candidate learns only from scored coverage events, then awaits NEW prospective outcomes. */
async function learn(a:Adapter,events:Forecast[],resolved:Map<string,Resolution>){
 events=await eventRows(a,'learning');const dailyGroups=new Map<string,Forecast[]>();for(const e of [...events].sort((x,y)=>x.issuedAt.localeCompare(y.issuedAt)||x.id.localeCompare(y.id))){const r=resolved.get(e.id);if(e.kind==='coverage'&&e.horizon==='day'&&r&&r.verifiedAt<=stamp(a)&&['TRUE','FALSE'].includes(r.outcome)){const day=e.issuedAt.slice(0,10);dailyGroups.set(day,[...(dailyGroups.get(day)??[]),e])}}
 const groups=new Map<string,Forecast>([...dailyGroups.entries()].map(([day,group])=>[day,group[parseInt(digest(day),36)%group.length]]));
 const after=await setting<string>(a,'brainLearningAfter',''),eligible=[...groups.values()].filter(e=>e.issuedAt>after),shadow=await setting<any>(a,'brainShadowModel',null);
 if(!shadow){if(eligible.length<50){await save(a,'brainLearning',{status:'Collecting verified daily cohorts',required:50,collected:eligible.length});return}const train=eligible.slice(-50),yes=train.filter(e=>resolved.get(e.id)!.outcome==='TRUE').length;if(yes<5||yes>45){await save(a,'brainLearning',{status:'Learning held: both outcome classes are required',required:50,collected:eligible.length});return}const intercept=fitCalibrationIntercept(train.map(e=>({raw:e.rawProbability,outcome:resolved.get(e.id)!.outcome==='TRUE'?1:0}))),model={id:BRAIN_VERSION+'-shadow-'+digest(stamp(a)),intercept,cutoff:stamp(a),status:'shadow',trainingCount:50};await a.db.prepare('INSERT INTO brain_models(id,created_at,data) VALUES(?,?,?) ON CONFLICT(id) DO NOTHING').bind(model.id,stamp(a),JSON.stringify(model)).run();await save(a,'brainShadowModel',model);await save(a,'brainLearning',{status:'Frozen candidate awaiting prospective daily cohorts',required:20,collected:0});return}
 const prospective=eligible.filter(e=>e.issuedAt>shadow.cutoff).slice(0,20);if(prospective.length<20){await save(a,'brainLearning',{status:'Prospective shadow validation',required:20,collected:prospective.length});return}const yes=prospective.filter(e=>resolved.get(e.id)!.outcome==='TRUE').length,candidate=brier(prospective.map(e=>({probability:calibrate(e.rawProbability,shadow.intercept),outcome:resolved.get(e.id)!.outcome==='TRUE'?1:0}))).brier!,champion=brier(prospective.map(e=>({probability:e.initialProbability,outcome:resolved.get(e.id)!.outcome==='TRUE'?1:0}))).brier!,promoted=yes>=5&&yes<=15&&candidate+.005<champion,result={...shadow,status:promoted?'active-preliminary':'rejected',candidateBrier:candidate,championBrier:champion,validationCount:20,evaluatedAt:stamp(a)};await a.db.prepare('INSERT INTO brain_models(id,created_at,data) VALUES(?,?,?) ON CONFLICT(id) DO NOTHING').bind(shadow.id+'-evaluation',stamp(a),JSON.stringify(result)).run();if(promoted)await save(a,'brainActiveModel',{id:shadow.id,intercept:shadow.intercept,status:'preliminary'});await save(a,'brainLearning',{status:promoted?'Candidate promoted; performance remains preliminary':'Candidate rejected; champion retained',required:20,collected:20,result});await save(a,'brainShadowModel',null);
 // Consumed outcomes cannot be reused to tune another candidate.
 await save(a,'brainLearningAfter',stamp(a));
}
export async function refreshBrain(a:Adapter){
 const at=stamp(a),input=await evidence(a),settings=await readBrainSettings(a),active=await setting<any>(a,'brainActiveModel',{id:BRAIN_VERSION,intercept:0});
 for(const item of input.items){const id='obs-'+await strongHash(canonicalObservation(item)),clusterKey=await strongHash(item.title.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim());await a.db.prepare('INSERT INTO brain_observations(id,cluster_key,source_id,first_seen,published_at,data) VALUES(?,?,?,?,?,?) ON CONFLICT DO NOTHING').bind(id,clusterKey,item.sourceId,at,item.publishedAt,JSON.stringify({...item,topics:topicsFor(item),topicRuleVersion:BRAIN_VERSION,origin:originForObservation(item)})).run()}
 const health=await setting<Record<string,any>>(a,'sourceHealth',{}),complete=a.complete===true&&input.coverage.omitted.olderThanLatestLimit===0&&input.sourceIds.length>0&&input.sourceIds.every(id=>health[id]?.status==='ok'&&Date.parse(health[id].lastCheck)>=Date.parse(at)-30*60000);
 await a.db.prepare('INSERT INTO brain_runs(at,fingerprint,complete) VALUES(?,?,?) ON CONFLICT(at) DO NOTHING').bind(at,input.fingerprint,complete?1:0).run();
 const runs=(await a.db.prepare('SELECT at,fingerprint,complete FROM brain_runs WHERE at>=? ORDER BY at').bind(new Date(Date.parse(at)-32*86400000).toISOString()).all<{at:string;fingerprint:string;complete:number}>()).results,start=new Date(Date.parse(at)-86400000).toISOString(),coverageReady=completeCoverage(runs,start,at,input.fingerprint);
 const observed=decode((await a.db.prepare('SELECT data,first_seen FROM brain_observations WHERE first_seen>=? ORDER BY first_seen').bind(start).all<{data:string;first_seen:string}>()).results).filter(i=>input.sourceIds.includes(i.sourceId)&&i.publishedAt>=start);
 const events=await eventRows(a),due=await eventRows(a,'due'),resolved=await resolutions(a);
 for(const event of [...due,...events.filter(e=>e.kind==='coverage')]){const prior=resolved.get(event.id);if(prior&&prior.outcome!=='UNKNOWN')continue;
  if(event.kind==='coverage'&&event.fingerprint===input.fingerprint){const hit=await a.db.prepare("SELECT data,first_seen FROM brain_observations WHERE first_seen>? AND first_seen<=? AND published_at>=? AND source_id IN (SELECT value FROM json_each(?)) AND EXISTS(SELECT 1 FROM json_each(json_extract(data,'$.topics')) WHERE value=?) AND json_extract(data,'$.topicRuleVersion')=? ORDER BY first_seen LIMIT 1").bind(event.issuedAt,event.deadline<at?event.deadline:at,event.issuedAt,JSON.stringify(event.sourceIds),event.topic,BRAIN_VERSION).first<{data:string;first_seen:string}>();if(hit){const item=JSON.parse(hit.data);await insertResolution(a,event.id,{outcome:'TRUE',eventOccurredAt:hit.first_seen,observedAt:at,verifiedAt:at,url:item.sourceUrl,sourceId:item.sourceId,reason:'A new dated, deduplicated matching report entered the frozen approved-source monitor within its forecast window. This verifies coverage only, not the reported event.',reviewer:'coverage monitor'});continue}if(event.deadline>at)continue;if(completeCoverage(runs,event.issuedAt,event.deadline,event.fingerprint)){await insertResolution(a,event.id,{outcome:'FALSE',eventOccurredAt:null,observedAt:at,verifiedAt:at,url:'https://the-current.sellery.chatgpt.site/ledger',reason:'No qualifying report entered the monitor during the frozen window; approved-source collection checkpoints covered the window with no gap over 95 minutes. This verifies monitor coverage only.',reviewer:'coverage monitor'});continue}}
  if(event.deadline>at)continue;
  if(!prior)await insertResolution(a,event.id,{outcome:'UNKNOWN',eventOccurredAt:null,observedAt:at,verifiedAt:at,url:'',reason:event.kind==='world'?'Deadline passed. Awaiting evidence-based owner verification.':'Deadline passed with incomplete collection coverage or a changed source roster. No negative outcome was inferred from missing news.',reviewer:'deadline monitor'});
 }
 const generated:Forecast[]=[];
 if(coverageReady){for(const topic of TOPICS){const count=independentEvidence(observed).filter(i=>topicsFor(i).includes(topic.id)).length;if(!count)continue;for(const horizon of HORIZONS.slice(0,2)){const issuedAt=at,id='coverage-'+topic.id+'-'+at.slice(0,10)+'-'+horizon.id+'-'+input.fingerprint;if(events.some(e=>e.id===id))continue;const rawProbability=coverageProbability(count,24,horizon.days*24);generated.push({id,kind:'coverage',question:'Will this monitor receive a new dated '+topic.name.toLowerCase()+' report by its deadline?',topic:topic.id,issuedAt,deadline:new Date(Date.parse(issuedAt)+horizon.days*86400000).toISOString(),initialProbability:calibrate(rawProbability,horizon.id==='day'?active.intercept:0),rawProbability,prior:coverageProbability(0,0,horizon.days*24),modelVersion:active.id,horizon:horizon.id,sourceIds:input.sourceIds,fingerprint:input.fingerprint,resolutionRule:'At least one new URL/title-deduplicated matching report is first observed within the issued/deadline window, published no earlier than issue, from the frozen approved-source roster. Rule version '+BRAIN_VERSION+'.',assumptions:'Gamma–Poisson coverage model, shape prior 0.5 and rate prior 24 hours; observed window 24 hours. Stationary reporting and a complete monitor are assumptions. Not a world-event probability.',definition:{count,exposureHours:24,topicRuleVersion:BRAIN_VERSION},evidence:input.items.filter(i=>topicsFor(i).includes(topic.id)).slice(0,12)})}}}
 for(const q of settings.questions.filter(q=>q.enabled&&q.deadline>at)){
  const id='world-'+q.id+'-'+digest(JSON.stringify({question:q.question,resolutionRule:q.resolutionRule,deadline:q.deadline})),existing=events.find(e=>e.id===id);if(resolved.has(id)&&resolved.get(id)?.outcome!=='UNKNOWN')continue;
  const result=bayesianQuestion(q,input.items,settings,at);if(!existing&&!result.evidence.length)continue;
  const definition={q,settings:{halfLifeHours:settings.halfLifeHours,likelihoodRatio:settings.likelihoodRatio,originCap:settings.originCap},sourceIds:input.sourceIds},rawProbability=result.probability,event:Forecast=existing??{id,kind:'world',question:q.question,topic:q.topic,issuedAt:at,deadline:q.deadline,initialProbability:rawProbability,rawProbability,prior:q.prior,modelVersion:BRAIN_VERSION,horizon:'custom',sourceIds:input.sourceIds,fingerprint:input.fingerprint,resolutionRule:q.resolutionRule,assumptions:q.priorBasis+' '+result.assumption,definition,evidence:result.evidence.map(e=>e.item)};
  const revision={probability:rawProbability,range:result.range,rangeLabel:'Evidence-weight sensitivity range',evidence:result.evidence,sourceIds:input.sourceIds,definition,assumptions:result.assumption,status:result.evidence.length?'experimental':'insufficient-evidence',createdAt:at,modelVersion:BRAIN_VERSION};
  const eventInsert=a.db.prepare('INSERT INTO forecast_events(id,issued_at,deadline,kind,probability,data) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(event.id,event.issuedAt,event.deadline,event.kind,event.initialProbability,JSON.stringify(event));
  const revisionInsert=a.db.prepare('INSERT INTO forecast_revisions(id,event_id,signature,created_at,data) VALUES(?,?,?,?,?) ON CONFLICT(event_id,signature) DO NOTHING').bind(crypto.randomUUID(),id,digest(JSON.stringify({evidence:result.evidence,definition})),at,JSON.stringify(revision));
  await a.db.batch([eventInsert,revisionInsert]);if(!existing)generated.push(event);
 }

 for(const event of generated)await a.db.prepare('INSERT INTO forecast_events(id,issued_at,deadline,kind,probability,data) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(event.id,event.issuedAt,event.deadline,event.kind,event.initialProbability,JSON.stringify(event)).run();
 await learn(a,[...events,...generated],await resolutions(a));await save(a,'brainLastRefresh',{at,coverageReady,reportCount:input.items.length,sourceCount:input.sourceIds.length,newForecasts:generated.length,complete});return setting(a,'brainLastRefresh',null);
}
function canonicalObservation(i:IntelligenceItem){const u=new URL(i.sourceUrl);u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(gclid|fbclid)$/i.test(k))u.searchParams.delete(k);return u.href.replace(/\/$/,'')}
function originForObservation(i:IntelligenceItem){return new URL(i.sourceUrl).hostname.replace(/^www\./,'')}
async function strongHash(value:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function getBrain(a:Adapter){
 const input=await evidence(a),events=await eventRows(a),resolved=await resolutions(a),revisions=await latestRevisions(a),at=stamp(a),lastRefresh=await setting<any>(a,'brainLastRefresh',null);
 const current=events.filter(e=>{
  if(e.deadline<=at||resolved.has(e.id))return false;
  if(e.kind==='coverage')return e.fingerprint===input.fingerprint&&e.sourceIds.every(id=>input.sourceIds.includes(id));
  const revision=revisions.get(e.id),contributors:IntelligenceItem[]=revision?revision.evidence.map((x:any)=>x.item):e.evidence;
  // A filtered evidence list cannot justify a probability that still includes withdrawn contributions.
  return input.sourceIds.length>0&&contributors.every(i=>input.sourceIds.includes(i.sourceId));
 }).map(e=>({...e,currentProbability:revisions.get(e.id)?.probability??e.initialProbability,evidence:e.evidence.filter(i=>input.sourceIds.includes(i.sourceId)),revision:revisions.get(e.id)?{...revisions.get(e.id),definition:undefined,evidence:revisions.get(e.id).evidence?.filter((x:any)=>input.sourceIds.includes(x.item.sourceId))}:null}));
 return {version:BRAIN_VERSION,at,collectedAt:input.collectedAt,status:input.items.length?'observing':'waiting',items:input.items,coverage:input.coverage,sourceCount:input.sourceIds.length,reportCount:input.items.length,lastRefresh,forecasts:current,pressure:newsPressure(input.items),topics:TOPICS.map(t=>({id:t.id,name:t.name,count:input.items.filter(i=>topicsFor(i).includes(t.id)).length,pathway:t.pathway,long:t.long})),horizons:HORIZONS,scores:await scoring(a,events,resolved),method:{name:'Jew Knows Signal Engine',status:'Experimental',collection:'Approved-source snapshots; reader network polls every 30 seconds while visible. Source collection is periodic, not an instantaneous wire.',coverage:'Coverage probabilities predict incoming reports, not whether a reported world event is true. Numerical estimates abstain until a complete 24-hour observation window exists.',formula:'P(at least one report) = 1 − ((24 + T) / (24 + T + h))^(0.5 + n)',world:'World-event estimates use declared priors and bounded, time-decayed keyword evidence. These are unvalidated assumptions, not established likelihoods.',longRange:'Month, year, five-year and ten-year views are conditional scenarios; no probability is invented.',risk:'Doomsday Monitor is a news stress index, not a countdown or probability of catastrophe.'}};
}
export async function getLedger(a:Adapter,eventId?:string,page=1){page=Math.max(1,Math.min(100000,Math.floor(Number(page)||1)));const input=await evidence(a),events=await eventRows(a,'history',eventId,page),resolved=await resolutions(a);const rows=events.filter(e=>!eventId||e.id===eventId).map(e=>({...e,evidence:e.evidence.filter(i=>input.sourceIds.includes(i.sourceId)),definition:undefined,sourceApproval:e.sourceIds.every(id=>input.sourceIds.includes(id))?'active':'changed',resolution:publicResolution(resolved.get(e.id),input.sourceIds),status:resolved.get(e.id)?.outcome??(e.deadline<=stamp(a)?'AWAITING VERIFICATION':'OPEN')}));let resolutionHistory:any[]=[];if(eventId)resolutionHistory=decode((await a.db.prepare('SELECT data FROM forecast_resolutions WHERE event_id=? ORDER BY verified_at,rowid').bind(eventId).all<{data:string}>()).results).map(r=>publicResolution(r,input.sourceIds));let revisions:any[]=[];if(eventId)revisions=decode((await a.db.prepare('SELECT data FROM forecast_revisions WHERE event_id=? ORDER BY created_at').bind(eventId).all<{data:string}>()).results).map(r=>({...r,evidence:r.evidence?.filter((e:any)=>input.sourceIds.includes(e.item.sourceId))}));const count=await a.db.prepare('SELECT COUNT(*) as count FROM forecast_events').first<{count:number}>();return {events:rows,revisions,resolutionHistory,page,total:count?.count??0,hasMore:page*200<(count?.count??0),scores:await scoring(a,events,resolved)}}
export async function readerKey(request:Request){const id=request.headers.get('oai-authenticated-user-id');if(!id)throw Error('Sign in to save a private personal briefing.');return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('jew-knows-profile:'+id)))].map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function getProfile(a:Adapter,key:string){const row=await a.db.prepare('SELECT data,updated_at FROM reader_profiles WHERE owner_key=?').bind(key).first<{data:string;updated_at:string}>();return {profile:row?JSON.parse(row.data):{zip:'',exposures:[],context:''},updatedAt:row?.updated_at??null}}
export async function saveProfile(a:Adapter,key:string,input:any){if(input.remove===true){await a.db.prepare('DELETE FROM reader_profiles WHERE owner_key=?').bind(key).run();return {removed:true}}const profile=validateProfile(input);await a.db.prepare('INSERT INTO reader_profiles(owner_key,data,updated_at) VALUES(?,?,?) ON CONFLICT(owner_key) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').bind(key,JSON.stringify(profile),stamp(a)).run();return {profile,updatedAt:stamp(a)}}
export async function personalBrief(a:Adapter,input:any){const profile=validateProfile(input),data=await evidence(a),inferredExposures=contextExposures(profile.context),combined={...profile,exposures:[...new Set([...profile.exposures,...inferredExposures])]};return {at:stamp(a),profile,inferredExposures,pathways:personalPathways(combined,data.items),basis:'Conditional exposure pathways from approved reporting. Context phrases can suggest additional exposure categories; they do not create facts or a personal probability. Your context stays on this Site and is not sent to local data providers.'}}

function publicResolution(r:Resolution|undefined,approved:string[]){if(!r)return null;if(r.sourceId&&!approved.includes(r.sourceId))return {...r,url:'',reason:'Resolution evidence has been withdrawn from public display.',reviewer:r.reviewer.startsWith('owner:')?'owner review':r.reviewer};return {...r,reviewer:r.reviewer.startsWith('owner:')?'owner review':r.reviewer}}
