import {isArmedConflictReporting,publicIntelligenceUrl,type IntelligenceItem} from './intelligence-core';

export const BRAIN_VERSION='signal-engine-1.0';
export const HORIZONS=[{id:'day',label:'Next day',days:1},{id:'week',label:'Next week',days:7},{id:'month',label:'Next month',days:30},{id:'year',label:'Next year',days:365},{id:'five',label:'5 years',days:1826},{id:'ten',label:'10 years',days:3652}] as const;
export type Horizon=typeof HORIZONS[number]['id'];
export const TOPICS=[
 {id:'security',name:'Conflict & security',terms:/\b(ceasefire|missile|shelling|armed conflict|airstrike|invasion|military offensive|hostage|war zone)\b/i,pathway:'Travel routes, insurance terms and supply chains may change if reported disruption persists.',long:'Diplomacy, security arrangements and transport resilience determine the longer-term path.'},
 {id:'economy',name:'Economy & supply',terms:/\b(inflation|interest rates?|tariff|recession|supply chain|oil prices?|energy prices?|shipping|unemployment|trade agreement)\b/i,pathway:'Changes in energy, borrowing or shipping costs can flow through to household and business budgets.',long:'Productivity, trade policy and energy investment determine whether cost pressure persists.'},
 {id:'technology',name:'Technology & AI',terms:/\b(artificial intelligence|AI|robotics?|semiconductor|data cent(?:er|re)|automation|machine learning)\b/i,pathway:'New tools or regulation may change how organizations buy technology and organize work.',long:'Adoption, competition, compute costs and regulation determine the extent of structural change.'},
 {id:'climate',name:'Weather & infrastructure',terms:/\b(hurricane|flood|wildfire|extreme heat|power outage|earthquake|storm warning|drought)\b/i,pathway:'Official alerts and infrastructure notices can affect travel, operations and near-term planning.',long:'Infrastructure investment, adaptation and insurance availability determine longer-term exposure.'},
 {id:'governance',name:'Policy & institutions',terms:/\b(election|legislation|congress|parliament|regulation|sanctions|supreme court|government shutdown|executive order)\b/i,pathway:'An enacted policy may change compliance or eligibility; reporting on proposals alone does not establish a change.',long:'Implementation, court review and future elections determine whether policy changes endure.'},
] as const;
export type TopicId=typeof TOPICS[number]['id'];
export type WorldQuestion={id:string;question:string;topic:TopicId;deadline:string;prior:number;priorBasis:string;resolutionRule:string;support:string[];contrary:string[];enabled:boolean};
export type BrainSettings={halfLifeHours:number;likelihoodRatio:number;originCap:number;questions:WorldQuestion[]};
export const DEFAULT_BRAIN_SETTINGS:BrainSettings={halfLifeHours:36,likelihoodRatio:1.35,originCap:3,questions:[]};
export type Profile={zip:string;exposures:string[];context:string};
export const EXPOSURES=[{id:'travel',label:'Travel & commuting',topics:['security','climate','economy']},{id:'household',label:'Household costs',topics:['economy','climate','governance']},{id:'business',label:'Business & operations',topics:['economy','governance','technology']},{id:'technology',label:'Technology & work',topics:['technology','governance']},{id:'supply',label:'Supply chains',topics:['security','economy','climate']}] as const;
export function scenarioFor(topic:TopicId,horizon:Horizon){const t=TOPICS.find(t=>t.id===topic)!;const frame={day:'Over the next day, look for fresh confirmation or a change in the reported situation.',week:'Over the next week, watch whether separate developments sustain or reverse this signal.',month:'Over the next month, implementation and persistence matter more than a single headline.',year:'Over the next year, repeated evidence and policy implementation determine whether the signal becomes a durable trend.',five:'The five-year scenario depends on sustained change across multiple economic and policy cycles.',ten:'The ten-year scenario is a structural hypothesis; future decisions can materially change its path.'}[horizon];return frame+' '+(['day','week'].includes(horizon)?t.pathway:t.long)}
export function contextExposures(context:string){const rules:[string,RegExp][]=[['business',/\b(business|retail|ecommerce|e-commerce|store|company|entrepreneur)\b/i],['travel',/\b(travel|flight|commut(?:e|ing)|trip)\b/i],['supply',/\b(import|export|shipping|inventory|manufacturer|supply chain)\b/i],['technology',/\b(software|developer|technology|automation|data|AI)\b/i],['household',/\b(household|family|home|utility|grocer(?:y|ies))\b/i]];return rules.filter(([,pattern])=>pattern.test(context)).map(([id])=>id)}
export function text(value:unknown,max=800){return String(value??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
export function digest(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
export function canonical(value:string){const u=new URL(value);u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(gclid|fbclid)$/i.test(k))u.searchParams.delete(k);return u.href.replace(/\/$/,'')}
export function topicsFor(item:Pick<IntelligenceItem,'title'|'excerpt'>):TopicId[]{const value=item.title+' '+item.excerpt;return TOPICS.filter(t=>t.id==='security'?isArmedConflictReporting(value):t.terms.test(value)).map(t=>t.id)}
export function originFor(item:IntelligenceItem){const content=item.title+' '+item.excerpt+' '+item.publisher;if(/\b(reuters)\b/i.test(content))return 'wire:reuters';if(/\b(associated press)\b|\(AP\)/i.test(content))return 'wire:ap';return new URL(item.sourceUrl).hostname.replace(/^www\./,'')}
export function independentEvidence(items:IntelligenceItem[]){const urls=new Set<string>(),titles=new Set<string>();return items.filter(item=>{const u=canonical(item.sourceUrl),t=item.title.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();if(urls.has(u)||titles.has(t))return false;urls.add(u);titles.add(t);return true})}
const logit=(p:number)=>Math.log(p/(1-p));
const sigmoid=(x:number)=>1/(1+Math.exp(-x));
export function coverageProbability(count:number,exposureHours:number,horizonHours:number){if(![count,exposureHours,horizonHours].every(Number.isFinite)||count<0||exposureHours<0||horizonHours<0)throw Error('Invalid observation window');return -Math.expm1(-(0.5+count)*Math.log1p(horizonHours/(24+exposureHours)))}
export function calibrate(raw:number,intercept=0){return sigmoid(logit(Math.max(.001,Math.min(.999,raw)))+Math.max(-.35,Math.min(.35,intercept)))}
export function fitCalibrationIntercept(rows:{raw:number;outcome:number}[]){if(!rows.length||!rows.some(r=>r.outcome===0)||!rows.some(r=>r.outcome===1))return 0;let low=-.35,high=.35;for(let step=0;step<60;step++){const mid=(low+high)/2,gradient=rows.reduce((n,r)=>n+calibrate(r.raw,mid)-r.outcome,0)/rows.length+.04*mid;if(gradient>0)high=mid;else low=mid}return (low+high)/2}
export function bayesianQuestion(question:WorldQuestion,items:IntelligenceItem[],settings:BrainSettings,at:string){
 const evidence: {item:IntelligenceItem;direction:number;weight:number;origin:string}[]=[];const origins=new Set<string>();
 for(const item of independentEvidence(items)){const value=(item.title+' '+item.excerpt).toLowerCase(),positive=question.support.some(t=>value.includes(t.toLowerCase())),negative=question.contrary.some(t=>value.includes(t.toLowerCase()));if(positive===negative||/\b(no|not|denied|false|rumou?r|unlikely)\b/i.test(value))continue;const origin=originFor(item);if(origins.has(origin)||origins.size>=settings.originCap)continue;const age=Math.max(0,(Date.parse(at)-Date.parse(item.publishedAt))/3600000),weight=Math.pow(2,-age/settings.halfLifeHours);origins.add(origin);evidence.push({item,direction:positive?1:-1,weight,origin});}
 const delta=evidence.reduce((n,e)=>n+e.direction*e.weight*Math.log(settings.likelihoodRatio),0);
 return {probability:sigmoid(logit(question.prior)+delta),range:[sigmoid(logit(question.prior)+delta*.5),sigmoid(logit(question.prior)+delta*1.5)].sort((a,b)=>a-b),evidence:evidence.map(e=>({...e,item:e.item})),assumption:'Keyword direction is a heuristic, not semantic verification. Prior and likelihood ratio are owner-declared assumptions.'};
}
export function validateBrainSettings(input:any):BrainSettings{
 const halfLifeHours=Number(input.halfLifeHours),likelihoodRatio=Number(input.likelihoodRatio),originCap=Number(input.originCap);
 if(!Number.isFinite(halfLifeHours)||halfLifeHours<6||halfLifeHours>168||!Number.isFinite(likelihoodRatio)||likelihoodRatio<1||likelihoodRatio>2||!Number.isInteger(originCap)||originCap<1||originCap>5)throw Error('Use a 6–168 hour half-life, a 1–2 likelihood ratio and 1–5 origin cap.');
 if(!Array.isArray(input.questions)||input.questions.length>12)throw Error('Use at most twelve measurable questions.');
 const ids=new Set<string>();const questions=input.questions.map((q:any)=>{const id=text(q.id,80),question=text(q.question,300),prior=Number(q.prior),deadline=new Date(q.deadline),priorBasis=text(q.priorBasis,600),resolutionRule=text(q.resolutionRule,900);if(!/^[a-zA-Z0-9_-]+$/.test(id)||ids.has(id)||!question||!TOPICS.some(t=>t.id===q.topic)||!Number.isFinite(prior)||prior<.01||prior>.99||!Number.isFinite(deadline.getTime())||!priorBasis||!resolutionRule)throw Error('Every question needs a unique ID, topic, deadline, 1–99% prior, prior basis and measurable resolution rule.');ids.add(id);const terms=(v:unknown)=>{if(!Array.isArray(v)||v.length>15)throw Error('Use up to fifteen keyword phrases.');return [...new Set(v.map(t=>text(t,80).toLowerCase()).filter(t=>t.length>=3))]};const support=terms(q.support),contrary=terms(q.contrary);if(!support.length)throw Error('A question needs a supporting phrase.');return {id,question,topic:q.topic,deadline:deadline.toISOString(),prior,priorBasis,resolutionRule,support,contrary,enabled:q.enabled===true}});
 return {halfLifeHours,likelihoodRatio,originCap,questions};
}
export function validateProfile(input:any):Profile{const zip=String(input.zip??'').trim();if(zip&&!/^\d{5}$/.test(zip))throw Error('Use a five-digit US ZIP code.');if(!Array.isArray(input.exposures)||input.exposures.some((id:unknown)=>!EXPOSURES.some(e=>e.id===id)))throw Error('Choose a supported area of exposure.');return {zip,exposures:[...new Set(input.exposures)] as string[],context:text(input.context,400)}}
export function personalPathways(profile:Profile,items:IntelligenceItem[]){return EXPOSURES.filter(e=>profile.exposures.includes(e.id)).map(e=>{const reports=independentEvidence(items).filter(i=>topicsFor(i).some(t=>(e.topics as readonly string[]).includes(t))).slice(0,3);return {id:e.id,label:e.label,status:reports.length?'conditional':'insufficient-evidence',bullets:reports.length?[...new Set(reports.flatMap(i=>topicsFor(i).filter(t=>(e.topics as readonly string[]).includes(t)).map(t=>TOPICS.find(x=>x.id===t)!.pathway)))]:['No matching approved-source evidence is available for this exposure.'],reports}})}
export function newsPressure(items:IntelligenceItem[]){if(!items.length)return {value:null,components:[],label:'Awaiting evidence'};const weights:{id:TopicId;weight:number}[]=[{id:'security',weight:.4},{id:'economy',weight:.25},{id:'climate',weight:.2},{id:'governance',weight:.15}],unique=independentEvidence(items);const components=weights.map(t=>({id:t.id,name:TOPICS.find(x=>x.id===t.id)!.name,weight:t.weight,share:unique.filter(i=>topicsFor(i).includes(t.id)).length/unique.length}));return {value:Math.round(100*components.reduce((n,c)=>n+c.weight*c.share,0)),components,label:'News stress index'}}
export function brier(rows:{probability:number;outcome:number;prior?:number}[]){if(!rows.length)return {count:0,brier:null,baseline:null,skill:null,bins:[]};const score=rows.reduce((n,r)=>n+(r.probability-r.outcome)**2,0)/rows.length,baseline=rows.every(r=>Number.isFinite(r.prior))?rows.reduce((n,r)=>n+(r.prior!-r.outcome)**2,0)/rows.length:null;return {count:rows.length,brier:score,baseline,skill:baseline&&baseline>0?1-score/baseline:null,bins:Array.from({length:5},(_,i)=>{const group=rows.filter(r=>Math.min(4,Math.floor(r.probability*5))===i);return {from:i*.2,to:(i+1)*.2,count:group.length,forecast:group.length?group.reduce((n,r)=>n+r.probability,0)/group.length:null,observed:group.length?group.reduce((n,r)=>n+r.outcome,0)/group.length:null}})}}
export function completeCoverage(runs:{at:string;fingerprint:string;complete:number}[],start:string,end:string,fingerprint:string,maxGapMinutes=95){
 const a=Date.parse(start),b=Date.parse(end),gap=maxGapMinutes*60000;if(!Number.isFinite(a)||!Number.isFinite(b)||b<a)return false;
 const ordered=runs.map(r=>({...r,time:Date.parse(r.at)})).filter(r=>r.time>=a-gap&&r.time<=b+gap).sort((x,y)=>x.time-y.time);
 const before=ordered.filter(r=>r.time<=a).at(-1),after=ordered.find(r=>r.time>=b);if(!before||!after)return false;
 const checkpoints=ordered.filter(r=>r.time>=before.time&&r.time<=after.time);if(checkpoints.some(r=>r.complete!==1||r.fingerprint!==fingerprint))return false;
 for(let i=1;i<checkpoints.length;i++)if(checkpoints[i].time-checkpoints[i-1].time>gap)return false;return true;
}
