import {publicIntelligenceUrl} from './intelligence-core';
import {text} from './forecast-core';
type Adapter={db:D1Database;now?:number};
const HEADERS={'User-Agent':'JewKnows/1.0 (+https://the-current.sellery.chatgpt.site/about)','Accept':'application/geo+json, application/json'};
async function fetchJson(url:string){const response=await fetch(url,{headers:HEADERS,redirect:'manual',signal:AbortSignal.timeout(12000)});if(!response.ok)throw Object.assign(Error('Provider returned '+response.status),{status:response.status});const reader=response.body?.getReader();if(!reader)throw Error('Provider returned no data');let bytes=0;const parts:Uint8Array[]=[];try{while(true){const {value,done}=await reader.read();if(done)break;bytes+=value.length;if(bytes>500000)throw Error('Provider response exceeded its bounded size');parts.push(value)}}finally{await reader.cancel().catch(()=>{})}const body=new TextDecoder().decode(Uint8Array.from(parts.flatMap(p=>[...p])));try{return JSON.parse(body)}catch{throw Error('Provider temporarily unavailable or rate limited')}}
async function cached(a:Adapter,key:string,ttl:number,fetcher:()=>Promise<any>){
 const now=a.now??Date.now(),row=await a.db.prepare('SELECT data,updated_at FROM cache WHERE key=?').bind(key).first<{data:string;updated_at:number}>(),old=row?JSON.parse(row.data):null;
 if(row&&(old?.retryAt>now||!old?.error&&now-row.updated_at<ttl))return {...old,cached:true};
 try{const data={value:await fetcher(),retrievedAt:new Date(now).toISOString(),stale:false};await a.db.prepare('INSERT INTO cache(key,data,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').bind(key,JSON.stringify(data),now).run();return {...data,cached:false}}
 catch(e){const data={value:old?.value??null,retrievedAt:old?.retrievedAt??null,stale:!!old?.value,error:'This information is temporarily unavailable.',notFound:(e as any)?.status===404,retryAt:now+60000};await a.db.prepare('INSERT INTO cache(key,data,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').bind(key,JSON.stringify(data),now).run();return data}
}
function indexedDate(value:unknown){const m=String(value).match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z$/);return m?`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}Z`:null}
export async function localIntelligence(a:Adapter,zip:string){
 if(!/^\d{5}$/.test(zip))throw Error('Enter a five-digit US ZIP code.');
 const placeData=await cached(a,'local-zip:'+zip,30*86400000,async()=>{const data=await fetchJson('https://api.zippopotam.us/us/'+zip),p=data.places?.[0];if(!p)throw Error('ZIP context was not found');const lat=Number(p.latitude),lon=Number(p.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<-90||lat>90||lon<-180||lon>180)throw Error('Invalid ZIP representative point');return {city:text(p['place name'],100),state:text(p.state,100),stateCode:text(p['state abbreviation'],2),lat,lon,additionalPlaces:Array.isArray(data.places)?data.places.length-1:0}});
 if(!placeData.value)return {zip,status:placeData.notFound?'not-found':'unavailable',place:null,weather:{value:null,error:'ZIP lookup unavailable'},news:{value:null,error:'ZIP lookup unavailable'},errors:[placeData.error],at:new Date(a.now??Date.now()).toISOString()};
 const place=placeData.value,point=place.lat+','+place.lon;
 const [weather,news]=await Promise.all([
  cached(a,'local-weather:'+zip,120000,async()=>{const result=await fetchJson('https://api.weather.gov/alerts/active?point='+encodeURIComponent(point));if(!Array.isArray(result.features))throw Error('Weather alert data did not validate');return result.features.slice(0,20).map((f:any)=>{const p=f.properties??{};return {id:text(f.id,300),url:publicIntelligenceUrl(f.id),event:text(p.event,160),headline:text(p.headline,500),severity:text(p.severity,40),certainty:text(p.certainty,40),effective:text(p.effective,50),expires:text(p.expires,50),area:text(p.areaDesc,500),issuer:text(p.senderName,150),instruction:text(p.instruction,2200)}})}),
  cached(a,'local-news:'+place.city.toLowerCase()+':'+place.stateCode,15*60000,async()=>{const time=a.now??Date.now(),lease=await a.db.prepare('INSERT INTO cache(key,data,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET updated_at=excluded.updated_at WHERE cache.updated_at<? RETURNING key').bind('gdelt-provider-throttle','{}',time,time-5500).first();if(!lease)throw Error('News provider is busy; retry shortly.');const u=new URL('https://api.gdeltproject.org/api/v2/doc/doc');u.search=new URLSearchParams({query:'"'+place.city.replace(/["\\]/g,'')+'" '+place.state.replace(/["\\]/g,''),mode:'ArtList',format:'json',maxrecords:'25',timespan:'7d',sort:'datedesc'}).toString();const result=await fetchJson(u.href);if(!Array.isArray(result.articles))throw Error('Local news data did not validate');return result.articles.flatMap((r:any)=>{const url=publicIntelligenceUrl(r.url),title=text(r.title,400),indexedAt=indexedDate(r.seendate);return url&&title&&indexedAt?[{url,title,publisher:new URL(url).hostname.replace(/^www\./,''),indexedAt,language:text(r.language,40)}]:[]})})
 ]);
 const validWeather=weather.value?.filter((alert:any)=>!alert.expires||Date.parse(alert.expires)>(a.now??Date.now()));
 const pathways=weather.error||weather.stale?[{title:'Weather updates are temporarily unavailable',condition:'Current official alerts could not be verified. Cached warnings may have expired.',action:'Check the National Weather Service directly.',url:'https://www.weather.gov/'}]:validWeather?.length?validWeather.map((alert:any)=>({title:alert.event,condition:'Official alert affecting the ZIP representative point; scope can extend beyond your location.',action:alert.instruction||'Read the issuing authority’s current guidance.',url:alert.url})):weather.error?[{title:'Weather updates are temporarily unavailable',condition:'An unavailable provider does not establish that conditions are safe.',action:'Check the National Weather Service directly.',url:'https://www.weather.gov/'}]:[{title:'No active alerts at the postal-city point',condition:'NWS returned no active alerts for this point. Conditions can differ across your ZIP code.',action:'Check updated official guidance before making location-specific decisions.',url:'https://www.weather.gov/'}];
 return {zip,status:placeData.error||weather.error||news.error?'partial':'ready',at:new Date(a.now??Date.now()).toISOString(),place,placeRetrievedAt:placeData.retrievedAt,placeStale:placeData.stale,placeError:placeData.error??null,weather,news,pathways,scope:'Approximate postal-city representative point; not your address, whole ZIP boundary, or verified incident location.',privacy:'ZIP is sent to Zippopotam.us, its representative coordinates to NWS, and city/state to GDELT. No personal profile or identity is sent.',attribution:[{name:'Zippopotam.us / GeoNames',url:'https://www.zippopotam.us/',license:'https://opendatacommons.org/licenses/odbl/'},{name:'National Weather Service',url:'https://www.weather.gov/documentation/services-web-api'},{name:'GDELT',url:'https://www.gdeltproject.org/'}]};
}
